// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/en/businessModel.ts
const data = {
  "description": [
    "Monetization via RaaS subscriptions, app-store ecosystem, custom development, and white-label platforms in the future."
  ],
  "kpi": {
    "arpu": "€3.0k–€4.0k / robot / month",
    "cac": "€4k–€8k",
    "grossMargin": "62–68%",
    "ltv": "€40k–€60k"
  },
  "partnerships": [
    "OEM partnerships (robotics manufacturers) for bundles & certifications",
    "System integrators for rollout, training and on-site maintenance",
    "Cloud/edge infrastructure (AWS/GCP) – security, observability, marketplaces",
    "Content/SDK partners – ROS2, tooling, safety/policy modules",
    "Research/universities for RL models, safety evaluations, talent pipeline"
  ],
  "pricing": [
    "Freemium (limited) • Basic €29 • Pro €99 • Enterprise from €299",
    "Discounts: 10% annual, 15% non-profits, 25% education"
  ],
  "revenueStreams": [
    {
      "description": "Monthly fee per robot including hardware, software license, maintenance/updates & support (SLA-tiered). Price range per robot: €3,000–€4,000 per month.",
      "type": "RaaS Subscription"
    },
    {
      "description": "Revenue share: platform 30% / developers 70% (enterprise: 15% / 85%). Expected volume: 5–15% of total revenue from year 3.",
      "type": "App Store Revenue Share"
    }
  ],
  "salesChannels": [
    "Direct sales (inbound/outbound) – demo flows, self-serve onboarding",
    "Partner/integrator network – OEMs, system integrators, regional resellers",
    "Developer ecosystem – app store, community, references/showcases",
    "Enterprise co-selling – cloud marketplaces, framework agreements",
    "Events/webinars – vertical use cases, design partner programs"
  ],
  "unitEconomics": [
    "RaaS price per robot: €3,000–€4,000 / month (Ø ~€3,500)",
    "Contribution per robot/month: ~€2,000–€2,400 after COGS (hardware, connectivity, support)",
    "Payback CAC: ~3 months (at ~€2,100 monthly contribution, CAC ~€6,000)",
    "LTV (contribution) ~€50,000 at 24 months retention; LTV/CAC > 7x",
    "Additional ARPU (user) ~€49 for software/services; upside via app purchases",
    "Gross margin 62–68% (software/platform share increasing)"
  ],
  "valueProp": [
    "RaaS – low upfront costs, predictable OPEX",
    "Platform ecosystem with app-store – skills and characters like apps",
    "SigmaCode AI – cloud/edge agents orchestrate secure, auditable workflows",
    "Fast integration (ROS2/SDK), enterprise security & compliance (EU AI Act/GDPR)"
  ]
} as const;

export default data;
