// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/en/chapters.ts
const data = {
  "businessModel": {
    "grantFitTitle": "Grant Fit (AWS / FFG)",
    "gtmTitle": "Go‑to‑market & Pilots",
    "moatTitle": "IP & Technical Moat",
    "overviewTitle": "Overview",
    "subtitle": "Business Model & Monetization"
  },
  "compliance": {
    "subtitle": "Compliance & Responsible AI"
  },
  "cover": {
    "title": "Cover"
  },
  "executive": {
    "subtitle": "Overview & Key Facts"
  },
  "executiveSummary": {
    "paragraphs": [
      "Value proposition: Humanoid AI robotics as RaaS with a robot app store and policy hub – certified skills are composed into end‑to‑end workflows, safely rolled out (CE/AI Act) and monitored fleet‑wide.",
      "Traction/KPIs: pilot fleet (logistics/manufacturing) in preparation, app store beta; target KPIs >99.99% uptime, <10ms edge response, >60% skill adoption per customer within 6 months.",
      "Funding ask: seed + grants for team, safety evidence and pilot fleet; use of funds: R&D/safety, app store/SDK, GTM partnerships, compliance/CE documentation."
    ],
    "sections": {
      "businessModel": {
        "content": "RaaS (subscription + usage) + skill licenses + marketplace fee. Enterprise rollouts with service and support plans.",
        "title": "Business Model"
      },
      "market": {
        "content": "Automation/reshoring megatrend. TAM >$40B by 2030 (Service Robotics & Humanoids). Strong demand in logistics, manufacturing, facility & service.",
        "title": "Market"
      },
      "problem": {
        "content": "Acute labor shortages, hazardous/monotonous tasks and fragmented IT/OT stacks constrain productivity. Traditional automation is inflexible, costly to change, and does not scale across sites and use cases.",
        "title": "Problem"
      },
      "solution": {
        "platform": {
          "content": "Humanoid AI robotics as RaaS with a robot app store: certified skills (grasping, navigation, inspection, handling) are composed into end‑to‑end workflows and deployed fleet‑wide.",
          "title": "Platform"
        },
        "technology": {
          "content": "Perception (multi‑sensor/VLM/3D), decision (planner/policies/safety), execution (force/impedance). RL/IL agents learn from demos & simulation; policy hub, tele‑assist, fleet learning, CE/AI Act compliance.",
          "title": "Technology"
        },
        "title": "Solution"
      },
      "usps": {
        "items": [
          "Robot app store: fast time‑to‑value, modular skills, vendor‑neutral",
          "Policy hub & safety guardrails: deterministic, auditable execution",
          "Fleet learning: continuous performance gains (RL/IL)",
          "99.99% uptime, <10ms edge response, zero‑downtime updates",
          "Enterprise integration (ERP/WMS/MES/IoT, digital twins)"
        ],
        "title": "USPs"
      }
    },
    "title": "Executive Summary"
  },
  "finance": {
    "subtitle": "Finance & KPIs"
  },
  "impact": {
    "subtitle": "Impact & Sustainability"
  },
  "market": {
    "subtitle": "Market & Competition"
  },
  "products": {
    "subtitle": "Products & Roadmap"
  },
  "risks": {
    "subtitle": "Risks & Mitigation"
  },
  "team": {
    "subtitle": "Team & Organization"
  },
  "technology": {
    "subtitle": "Technology & Architecture"
  }
} as const;

export default data;
