// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/en/closingPage.ts
const data = {
  "legal": "Confidential — for evaluation purposes only.",
  "next": {
    "title": "Suggested next step"
  },
  "prepared": "Prepared on",
  "qr": {
    "desc": "Scan the QR to open the live version or book a meeting."
  },
  "subtitle": "Thank you for your interest — we look forward to speaking.",
  "title": "Contact & Next Steps"
} as const;

export default data;
