// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/en/company.ts
const data = {
  "industry": "Robotics / AI / Industrial Automation",
  "legal": {
    "entity": "GmbH (planned)",
    "founding": "2025",
    "hq": "Vienna, Austria"
  },
  "location": "Vienna, Austria (EU)",
  "milestones": [
    "2025 – Foundations & prototypes",
    "2026 – Pilot fleet & safety",
    "2027 – App store beta",
    "2028 – Enterprise rollout"
  ],
  "mission": "Make humanoid robotics practical, safe and auditable – with modular skills, policy hub and an enterprise‑ready app store.",
  "name": "SIGMACODE AI Robotics GmbH (planned)",
  "team": "AI/Robotics, Controls, Cloud, Product",
  "vision": "A curated app‑ecosystem and safe humanoid assistance for everyday industrial work."
} as const;

export default data;
