// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/en/compliance.ts
const data = {
  "aiAct": [
    "Risk management, data/model governance, logging/audit",
    "Transparency/explainability, human oversight"
  ],
  "aws": [
    "Funding criteria (DeepTech, safety, EU competitiveness)",
    "Use‑case fit (productivity, safe human/robot collaboration)"
  ],
  "privacy": [
    "Privacy by design, data minimization, edge inference",
    "Provenance/lineage, model cards/data sheets"
  ],
  "safety": [
    "Zone/contact‑force guardrails, collaborative trajectories",
    "CE documentation, E‑stop, fail‑safe mechanisms"
  ],
  "safetyStandards": [
    "CE guidelines",
    "ISO 10218",
    "ISO/TS 15066",
    "EU AI Act (high‑risk)"
  ],
  "securityProgram": [
    "Threat modeling, pen tests, SLAs",
    "IAM/least privilege, secrets mgmt, zero trust"
  ]
} as const;

export default data;
