// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/en/content.ts
const data = {
  "company": {
    "industry": "AI Robotics / Software",
    "location": "Vienna, Austria",
    "mission": "Robot skills as apps – secure, auditable, scalable",
    "name": "SIGMACODE AI GmbH",
    "team": "Core team 6 FTE, hiring focus AI/Robotics",
    "vision": "Humanoid AI robotics that makes work safer and more productive"
  },
  "market": {
    "sam": "Industrial segments with high need: logistics, manufacturing, facility & service – initial focus corridors with clear willingness to pay.",
    "som": "Pilot regions with enterprise rollouts (DACH/EU) and partner ecosystem – scalable via app store and fleet deployments.",
    "tam": ">$40B by 2030 (Service Robotics & Humanoids) – driven by automation, reshoring and demographics."
  },
  "solution": {
    "agents": "RL/IL agents: learn from demos & simulation (policy hub)",
    "appstore": "Robot app store: certified skills, marketplace & billing",
    "integration": "Enterprise integration: ERP/WMS/MES/IoT, digital twins",
    "rass": "Robot-as-a-Service: subscription + usage with fleet management",
    "usp": "Guardrails & compliance (CE/AI Act), zero-downtime deployments"
  }
} as const;

export default data;
