// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/en/costPlan.ts
const data = {
  "budgetByYear": {
    "headers": [
      "Year",
      "Amount"
    ],
    "rows": [
      [
        "2025",
        760
      ],
      [
        "2026",
        820
      ],
      [
        "2027",
        890
      ],
      [
        "2028",
        940
      ],
      [
        "2029",
        980
      ]
    ],
    "title": "Budget by year (k€)"
  },
  "budgetRows": [
    [
      "R&D",
      "€420k",
      "42%"
    ],
    [
      "Go‑to‑market",
      "€260k",
      "26%"
    ],
    [
      "Hardware",
      "€160k",
      "16%"
    ],
    [
      "Operations",
      "€110k",
      "11%"
    ],
    [
      "Compliance",
      "€50k",
      "5%"
    ]
  ],
  "capexOpex": {
    "headers": [
      "Category",
      "Amount"
    ],
    "rows": [
      [
        "CAPEX – Robots/Compute",
        110
      ],
      [
        "CAPEX – Sensors",
        15
      ],
      [
        "OPEX – Cloud/Inference",
        35
      ],
      [
        "OPEX – Proxies/Scraping",
        12
      ]
    ],
    "title": "CAPEX / OPEX (k€)"
  },
  "hardwareBreakdown": {
    "headers": [
      "Category",
      "Amount"
    ],
    "rows": [
      [
        "Humanoid robots – Model A (2 units)",
        90
      ],
      [
        "Humanoid robots – Model B (1 unit)",
        45
      ],
      [
        "Sensor packs (RGB‑D/LiDAR/IMU)",
        10
      ],
      [
        "End effectors (gripper/force)",
        6
      ],
      [
        "Compute (Jetson Orin/Edge‑GPU)",
        5
      ],
      [
        "Sim licenses/assets",
        2
      ],
      [
        "Datasets (commercial licenses)",
        2
      ]
    ],
    "title": "Hardware details (k€)"
  }
} as const;

export default data;
