// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/en/coverPage.ts
const data = {
  "companyName": "Investors & Funding Agencies",
  "confidentialNotice": "Confidential – for evaluation purposes only. Do not distribute without consent of SIGMACODE AI Robotics.",
  "confidential": "Confidential & proprietary. This document contains proprietary information intended solely for the addressed recipients. Any disclosure, duplication or publication – in whole or in part – is prohibited without prior written consent.",
  "cta": {
    "goToChapterOne": "Go to Chapter 1"
  },
  "date": "Date",
  "openPitch": "Open pitch deck",
  "preparedFor": "Prepared for",
  "versionLabel": "Version",
  "version": "v1.0",
  "subtitle": "Specialized in the humanoid‑robotics app store: household robots as a service (RaaS) – everyday tasks, modular apps and seamless updates. Our platform unifies hardware, app ecosystem and AI assistance for real‑world use at home – scalable today, standard tomorrow. With a partner ecosystem, security by design and privacy at the core, we pave the way for practical humanoid assistance.",
  "title": "Humanoid Robots as a Service",
  "contact": {
    "title": "Contact",
    "person": "Contact person",
    "personName": "Michael S. (Managing Director)",
    "email": "Email",
    "emailAddress": "contact@sigmacode.ai",
    "phone": "Phone",
    "phoneNumber": "+43 660 0000000",
    "address": "Address",
    "addressValue": "SIGMACODE AI Robotics · Vienna, Austria"
  },
  "value": {
    "aas": "Agents as a Service · Tasks over apps",
    "appstore": "Curated AI app ecosystem · Developer store",
    "humanoid": "Humanoid robotics · practical & safe"
  }
} as const;

export default data;
