// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/en/cv.ts
const data = {
  "actionsLabel": "CV Actions",
  "availability": "Available: Part-time · Project-based",
  "backToPlan": "Back to Business Plan",
  "contact": {
    "copied": "Copied",
    "copyEmail": "Copy email",
    "copyEmailAria": "Copy email address",
    "email": "ismet@mesic.dev",
    "github": "",
    "label": "Contact",
    "linkedin": "",
    "open": "Open:"
  },
  "details": "Details",
  "fallback": [
    {
      "bullets": [
        "—",
        "—"
      ],
      "period": "2021–Present",
      "subtitle": "—",
      "title": "Senior Executive"
    },
    {
      "bullets": [
        "—"
      ],
      "period": "2018–2021",
      "subtitle": "—",
      "title": "Executive"
    }
  ],
  "items": [
    {
      "bullets": [
        "Acquisition of Z-Line Automotive with €10.4 million in debt",
        "Successful turnaround and securing 150 jobs",
        "New foundation of Cutting Edge d.o.o. with €1.2 million startup capital",
        "Company value growth to over €10 million through new orders and investors",
        "Acquisition of new shareholders: Recaro Automotive (DE) 🇩🇪 (20%), Gruppo Mastrotto (IT) 🇮🇹 (15%; €1.5 million)"
      ],
      "period": "05/2022 – 02/2024",
      "subtitle": "Z-Line Automotive (Slovenia) 🇸🇮 → Cutting Edge d.o.o.",
      "title": "Turnaround Expert & CEO"
    },
    {
      "bullets": [
        "Building an international trading company for medical devices (Austria, Germany, Slovakia)",
        "State-listed procurement partner since 2021",
        "Scaling the company in medical technology & procurement",
        "Handed over company to focus on Robotics & AI"
      ],
      "period": "2020 – 2022",
      "subtitle": "Servacon GmbH (AT/DE) 🇦🇹🇩🇪 & Servacon s.r.o. (SK) 🇸🇰",
      "title": "CEO & Owner"
    },
    {
      "bullets": [
        "Establishment and management of a Covid-PCR testing laboratory",
        "Development & implementation of testing strategy during the pandemic",
        "Coordination with authorities (B&B and B&C)"
      ],
      "period": "01/2022 – 06/2023",
      "subtitle": "PCR-Labor Kuhn & Mather OG (AT) 🇦🇹",
      "title": "Head & Co-Founder"
    },
    {
      "bullets": [
        "Building and managing an online pharmacy shop",
        "Strategic consulting on digitalization & process optimization",
        "Development of Covid-19 testing strategies during the pandemic"
      ],
      "period": "2018 – 2021",
      "subtitle": "MediStore.at (AT) 🇦🇹",
      "title": "Strategic Advisor & IT Architect"
    },
    {
      "bullets": [
        "Summary: Crypto advisory, trading, GPU mining (Luleå/SE) & mining farm (Priboj/RS)",
        "Consortium with partners: jointly developed/deployed mining hardware & infrastructure (SE/RS)",
        "Roles: Founder/CEO, shareholder, operator; total investment > €2.6M"
      ],
      "period": "2016 – 2020",
      "subtitle": "Overview",
      "title": "Crypto & Mining"
    },
    {
      "bullets": [
        "Development of blockchain solutions, smart contracts and Web3 projects",
        "Early research in decentralization and digital assets"
      ],
      "period": "from 2014",
      "subtitle": "Blockchain Development",
      "title": "Software Developer & Innovator"
    },
    {
      "bullets": [
        "Building and managing an Apple Store with locations in Viennas 13th and 9th districts",
        "Certified Apple Technician and official Apple Service Provider",
        "Responsibility for sales, service and team management",
        "Team size: up to 15 employees",
        "Growth: scaled ~2.25x per location; after opening a second store total ~4x output (no monetary figures)"
      ],
      "period": "2010 – 2022",
      "subtitle": "McPlus Multimedia (AT) 🇦🇹",
      "title": "Founder & CEO"
    },
    {
      "bullets": [
        "Founded an IT service company at age 14",
        "Computer and network support for private and business customers",
        "Team size: 1 (self-employed)"
      ],
      "period": "2008 – 2010",
      "subtitle": "Computernotruf.at (AT) 🇦🇹",
      "title": "Founder & CEO"
    },
    {
      "bullets": [
        "Founded and led a white-hat hacker group",
        "Collaboration with the Anonymous collective in international security projects",
        "Focus on IT security, network security & ethical hacking"
      ],
      "period": "2004 – 2008",
      "subtitle": "ISA (International Security Alliance) – White-Hat Hacker Crew",
      "title": "Founder & Leader"
    },
    {
      "bullets": [
        "Built a forum platform with over 20,000 registered users",
        "Early community and platform development in social media environment"
      ],
      "period": "2004 – 2006",
      "subtitle": "msn-icq-board.com",
      "title": "Founder & Operator"
    },
    {
      "bullets": [
        "Leadership and strategic development of associations promoting research & innovation",
        "Building international networks between science, technology and industry"
      ],
      "period": "2018 – Present",
      "subtitle": "RCIID (Rocket Chain Institute for International Development)",
      "title": "President"
    },
    {
      "bullets": [
        "Blockchain & AI research and development (Metanetwork)",
        "Pre-research underpinning this business plan",
        "Jointly developed mining hardware (with partners)",
        "Exclusive partnerships in China (CN) 🇨🇳: Pandaminer & Pangolinminer (mining hardware)",
        "Strategy: repurpose GPU hardware for AI after mining (lifetime value, preparing for the AI boom)"
      ],
      "period": "2017 – Present",
      "subtitle": "Metanetwork – Blockchain & AI Research & Development",
      "title": "Head of Research & Development"
    },
    {
      "bullets": [
        "Coaching and mentoring several innovative startups",
        "Support in early-adopter phase, including Socialswap.io"
      ],
      "period": "2016 – Present",
      "subtitle": "Early-Bird Projects",
      "title": "Coach & Mentor"
    },
    {
      "bullets": [
        "Co-organization and strategic support of a nation-wide MMA event (largest MMA event in Austria, Wiener Stadthalle)",
        "Research & investigations related to the event series",
        "Sparta Reality Show (YouTube): https://www.youtube.com/watch?v=xtxf_VKw1mg",
        "Key accounts: enterprise clients, sponsors, VIP & influencer relations",
        "Mentoring of athletes & business partners"
      ],
      "period": "2020 – Present",
      "subtitle": "Sparta CF (AT) – MMA Austria 🇦🇹",
      "title": "Organizer & Strategic Partner/Mentor"
    },
    {
      "bullets": [
        "Development of innovative projects in AI, robotics and digitalization",
        "Author of the book \"#Sigmacode – The mental operating system for men\""
      ],
      "period": "2022 – Present",
      "subtitle": "Other Projects & Engagements",
      "title": "Project Development"
    },
    {
      "bullets": [
        "Collaboration with police in solving cybercrime and digital offenses",
        "Application of IT forensics and hacker expertise for investigation purposes",
        "Data analysis and statistical preparation of complex file records",
        "Supporting lawyers through precise data preparation, referencing and case preparation",
        "Active in several ongoing cases (2022 – present)"
      ],
      "period": "Ongoing",
      "subtitle": "Collaboration with Police & Lawyers",
      "title": "IT Security, Forensics & Legal Data Analytics"
    }
  ],
  "languages": {
    "items": [
      {
        "level": "Native",
        "name": "German"
      },
      {
        "level": "Native",
        "name": "Bosnian"
      },
      {
        "level": "Fluent",
        "name": "English"
      }
    ],
    "title": "Languages"
  },
  "less": "Show less",
  "location": "Vienna, AT",
  "metrics": {
    "experience": "Experience",
    "experienceValue": "20+ years",
    "focus": "Focus",
    "focusValue": "AI, Robotics, Turnaround",
    "stack": "Stack",
    "stackValue": "AI • Robotics • Python • Cloud • Web3"
  },
  "more": "Show more",
  "noDetails": "No details available",
  "openFullView": "Open Full View",
  "pageSubtitle": "Executive – Entrepreneur, Innovator, Turnaround, Mentor & Researcher",
  "pageTitle": "Curriculum Vitae – Ismet Mesic",
  "performance": {
    "items": [
      {
        "company": "Cutting Edge d.o.o.",
        "description": "Turnaround and restructuring from 1.2M€ to over 10M€ company value",
        "employees": 150,
        "growth": 775,
        "period": "05/2022 – 02/2024",
        "value": 10.5
      },
      {
        "company": "PCR-Labor Kuhn & Mather OG (AT) 🇦🇹",
        "description": "PCR lab build & operations; start capital €0.25M, result: ~€2.2M profit (ROI: +880%)",
        "growth": 880,
        "period": "01/2022 – 06/2023",
        "value": 2.2,
        "startCapital": 0.25
      },
      {
        "company": "Servacon GmbH & s.r.o. (AT/DE/SK) 🇦🇹🇩🇪🇸🇰",
        "description": "Building and scaling in medical technology with government recognition",
        "employees": 25,
        "growth": 280,
        "period": "2020 – 2022",
        "value": 2.8
      },
      {
        "company": "Multiple Projects",
        "description": "Various IT-Security and Blockchain projects with international focus",
        "employees": 12,
        "growth": 150,
        "period": "2018 – 2020",
        "value": 1.5
      },
      {
        "company": "IT-Security & Forensics",
        "description": "Building security infrastructures and forensics expertise",
        "employees": 8,
        "growth": 120,
        "period": "2015 – 2018",
        "value": 0.8
      },
      {
        "company": "Sparta CF (MMA Austria) 🇦🇹",
        "description": "Professionalized event series, expanded sponsorship & ticketing",
        "employees": 10,
        "growth": 95,
        "period": "2021 – Present",
        "value": 0.35
      },
      {
        "company": "Miss Germany Organization",
        "description": "Business & media partnerships, scaled reach and collaborations",
        "employees": 20,
        "growth": 60,
        "period": "2019 – 2021",
        "value": 1.2
      },
      {
        "company": "Global Forensic Alliance",
        "description": "Built an international forensics community and services",
        "employees": 9,
        "growth": 85,
        "period": "2017 – 2019",
        "value": 0.9
      },
      {
        "company": "McPlus Multimedia (AT) 🇦🇹",
        "description": "Retail scaling: ~2.25x per store; with second store total ~4x (no monetary figures)",
        "growth": 300,
        "period": "2010 – 2022",
        "series": [1, 2.25, 4.0]
      },
      {
        "company": "mscinvest d.o.o.",
        "description": "Crypto consulting; generated profit ~€0.8M (no speculative gains)",
        "growth": 100,
        "period": "2017 – 2020",
        "value": 0.8
      },
      {
        "company": "coin2cash s.r.o.",
        "description": "Shareholder; international OTC crypto trading",
        "growth": 100,
        "period": "2017 – 2019",
        "value": 0.5
      },
      {
        "company": "bitunity GmbH – Luleå (SE) 🇸🇪",
        "description": "GPU mining farm; investment volume ~€2.0M",
        "growth": 100,
        "period": "2016 – 2018",
        "value": 2.0
      },
      {
        "company": "Mining Farm Priboj (RS) 🇷🇸",
        "description": "Mining farm operations; investment volume ~€0.6M",
        "growth": 100,
        "period": "2018 – 2019",
        "value": 0.6
      }
    ],
    "title": "Performance Track Record"
  },
  "period": "Period",
  "photo": "/cv/profile.jpg",
  "print": "Print",
  "printDescription": "Prints the current page and saves it as PDF",
  "press": {
    "title": "Press & Media"
  },
  "role": "Executive Entrepreneur & Innovation Architect",
  "saveAsPdf": "Save as PDF",
  "skills": {
    "categories": [
      {
        "items": [
          "Programming experience since age 12",
          "Python, Blockchain, Web, GPU, AI",
          "Apple Technology (certified Apple Technician)"
        ],
        "name": "Technology"
      },
      {
        "items": [
          "Corporate turnaround (up to 150 employees)",
          "Company values up to double-digit million range",
          "Business Development & international partnerships"
        ],
        "name": "Entrepreneurship"
      },
      {
        "items": [
          "Medical Technology & Government Procurement",
          "IT Security & Forensics",
          "Strategic Logistics Planning & Supply Chain Management"
        ],
        "name": "Industry Experience"
      },
      {
        "items": [
          "Coaching & Mentoring of Startups & Projects",
          "Event Organization (Sports & Business)",
          "Community Management (20,000+ user platform)"
        ],
        "name": "Leadership"
      }
    ],
    "title": "Skills & Expertise"
  },
  "summary": {
    "bullets": [
      "Turnaround & Scale: Turnaround leader (secured 150+ jobs, company value > €10M)",
      "Technology: AI & Robotics, Cloud/Edge, Safety — focus on auditable systems",
      "Product: App Store/SDK, partner ecosystem, developer enablement",
      "Author: #Sigmacode — the mental operating system for men",
      "Leadership & Network: coaching, mentoring, international collaboration",
      "FinOps & ROI: efficiency, cost control, sustainable profitability"
    ],
    "title": "Executive Summary"
  },
  "title": "Curriculum Vitae",
  "viewFull": "View full CV",
  "workMode": "Remote‑first | DACH"
} as const;

export default data;
