// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/en/exit.ts
const data = {
  "buyers": {
    "financial": [
      "Growth equity funds",
      "Sector‑focused PE"
    ],
    "strategic": [
      "Odds platforms",
      "Data providers",
      "Sports media",
      "US sportsbooks"
    ],
    "title": "Potential buyers"
  },
  "coInvest": {
    "points": [
      "Strategic co‑investment with GTM partners",
      "Syndicated SPV for strategic buyers"
    ],
    "title": "Co‑investment structures"
  },
  "earnOut": {
    "mechanics": [
      "Performance‑based tranches (ARR/EBITDA milestones)",
      "Equity vesting tied to retention",
      "Clawback clauses for extraordinary events"
    ],
    "title": "Earn‑out mechanisms"
  },
  "notes": "High strategic interest due to AI/robotics consolidation; co-selling/alliances increase valuation options.",
  "options": {
    "a": {
      "points": [],
      "title": "Trade sale (strategic)"
    },
    "b": {
      "points": [],
      "title": "PE / growth buyout"
    },
    "c": {
      "points": [],
      "title": "IPO (long-term option)"
    }
  },
  "preparation": {
    "actions": [
      "Bankable KPIs: audited ARR, churn <10%, gross margin >60%",
      "Compliance readiness: CE, AI Act, privacy",
      "Data room: contracts, IP, tech docs, security reports"
    ],
    "title": "Exit preparation"
  },
  "risks": {
    "items": [
      {
        "mitigation": "Dual‑track process (IPO/trade sale), flexible timing",
        "risk": "Market window shifts"
      },
      {
        "mitigation": "Broaden buyer universe (strategic/financial)",
        "risk": "Buyer concentration"
      },
      {
        "mitigation": "Early certification, legal counsel",
        "risk": "Regulatory delays"
      }
    ],
    "title": "Exit risks & mitigations"
  },
  "roi": {
    "text": "Illustrative scenarios show attractive multiples under conservative growth assumptions.",
    "title": "ROI & investor value"
  },
  "secondary": {
    "points": [
      "Partial founder liquidity at Series A/B",
      "Employee liquidity via tender offer"
    ],
    "title": "Secondary options"
  },
  "timeline": {
    "phases": [
      {
        "activities": [
          "Scale ARR > €10M",
          "Keep unit economics stable"
        ],
        "period": "2026–2027"
      },
      {
        "activities": [
          "EBITDA positive",
          "Broaden buyer universe"
        ],
        "period": "2028–2029"
      },
      {
        "activities": [
          "Exit window (IPO or trade sale)"
        ],
        "period": "2030+"
      }
    ],
    "title": "Exit timeline"
  },
  "title": "Exit strategy",
  "valuation": {
    "methods": [
      "Revenue multiples (ARR forward)",
      "Comparable transactions",
      "Discounted cash flow (sensitivity)"
    ],
    "multiples": [
      "EV/ARR 8–12x",
      "EV/EBITDA 15–25x"
    ],
    "range": "€30–60M (illustrative)",
    "title": "Valuation approach"
  }
} as const;

export default data;
