// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/en/financePlanDetailed.ts
const data = {
  "capexOpex": {
    "CAPEX": [
      [
        "Robots",
        160
      ],
      [
        "Tools",
        40
      ]
    ],
    "OPEX": [
      [
        "Cloud",
        120
      ],
      [
        "Support",
        80
      ]
    ]
  },
  "ebitdaByYear": {
    "headers": [
      "Year",
      "EBITDA"
    ],
    "rows": [
      [
        2025,
        -200
      ],
      [
        2026,
        -60
      ],
      [
        2027,
        80
      ],
      [
        2028,
        220
      ],
      [
        2029,
        400
      ]
    ],
    "title": "EBITDA by year (k€)"
  },
  "personnel": [
    [
      2025,
      "€420k"
    ],
    [
      2026,
      "€620k"
    ],
    [
      2027,
      "€820k"
    ],
    [
      2028,
      "€980k"
    ]
  ],
  "revenueHeaders": [
    "Stream",
    "Amount"
  ],
  "revenueRows": [
    [
      "Platform",
      1400
    ],
    [
      "App store",
      900
    ]
  ],
  "revenueTitle": "Revenue breakdown (k€)",
  "totalsHeaders": [
    "Category",
    "Amount"
  ],
  "totalsRows": [
    [
      "Revenue",
      2300
    ],
    [
      "COGS",
      700
    ],
    [
      "OPEX",
      1000
    ],
    [
      "EBITDA",
      400
    ]
  ],
  "totalsTitle": "Totals (k€)"
} as const;

export default data;
