// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/en/gtm.ts
const data = {
  "channelMix": [
    {
      "channel": "Alliances (OEM/integrator)",
      "metrics": [
        "Partner pipeline",
        "Co‑seller deals"
      ],
      "notes": "Leverage existing customer bases",
      "share": 35
    },
    {
      "channel": "Design partners/direct",
      "metrics": [
        "SQLs",
        "PoC starts"
      ],
      "notes": "Rapid validation, references",
      "share": 25
    },
    {
      "channel": "Developer/marketplace",
      "metrics": [
        "SDK signups",
        "Third‑party skills"
      ],
      "notes": "Ecosystem growth, rev share",
      "share": 15
    },
    {
      "channel": "Events & demos",
      "metrics": [
        "Leads",
        "Demo requests"
      ],
      "notes": "Live experience, trust",
      "share": 10
    },
    {
      "channel": "Content/SEO/community",
      "metrics": [
        "Visits",
        "MQL rate"
      ],
      "notes": "Long‑term demand gen",
      "share": 10
    },
    {
      "channel": "Paid (targeted ABM)",
      "metrics": [
        "CTR",
        "CPL"
      ],
      "notes": "Tightly focused on ICP accounts",
      "share": 5
    }
  ],
  "funnel": [
    {
      "metric": "Reach/Impressions",
      "notes": "Paid + earned media, social video demos",
      "stage": "Awareness",
      "target": ">500k/qtr"
    },
    {
      "metric": "Website visits / demo views",
      "notes": "SEO, tech blog, benchmark videos",
      "stage": "Interest",
      "target": ">60k/qtr"
    },
    {
      "metric": "Qualified leads (MQL)",
      "notes": "Lead magnets, whitepapers, webinars",
      "stage": "Consideration",
      "target": "3.5% of visits"
    },
    {
      "metric": "SQL/design partners",
      "notes": "Use‑case scoping, ROI simulator",
      "stage": "Evaluation",
      "target": "40% of MQL"
    },
    {
      "metric": "PoC start",
      "notes": "On‑site demos, integrator support, SLAs",
      "stage": "Pilot",
      "target": ">50% of SQL"
    },
    {
      "metric": "Multi‑site deployments",
      "notes": "Enablement, training, analytics",
      "stage": "Rollout",
      "target": ">60% of pilots"
    },
    {
      "metric": "Net expansion",
      "notes": "App‑store upsell, new skills/use cases",
      "stage": "Expansion",
      "target": ">120%"
    }
  ],
  "kpis": [
    ">99.99% uptime (rolling 30d)",
    "<10ms edge response",
    ">60% skill adoption per customer",
    ">3 active skills per robot after 90 days",
    "Net expansion >120%",
    "Sales cycle <90 days (pilot → rollout)",
    "PoC conversion >50%"
  ],
  "phase1": [
    "Pilot projects with nursing homes, hotels, research institutes",
    "Cooperations with Austrian universities (TU Wien, FH Hagenberg, JKU Linz)",
    "Scale (Phase 2 – 2028–2029): build RaaS infrastructure for B2B customers, launch robot app store (beta), target 20–30 customers in DACH",
    "Expansion (Phase 3 – 2030): enter EU market (healthcare + office), white‑label solutions for international partners, app store as standard ecosystem for humanoid robots"
  ],
  "phases": [
    {
      "items": [
        "PoC in logistics/manufacturing",
        "Define SLA/support model",
        "Partner onboarding (integrators, OEMs)"
      ],
      "name": "Phase 1 – pilots"
    },
    {
      "items": [
        "Developer SDK",
        "Third‑party skills",
        "Billing/licensing"
      ],
      "name": "Phase 2 – app store beta"
    },
    {
      "items": [
        "Multi‑site deployments",
        "Analytics/KPIs",
        "Enablement & training"
      ],
      "name": "Phase 3 – enterprise rollout"
    }
  ],
  "tactics": [
    "Design partner program (3–5 lighthouse customers)",
    "Alliances with robotics OEMs & integrators",
    "Developer program for skill providers (rev share)",
    "Certifications/CE/AI Act as market enabler",
    "Showcases & demos (trade fairs, labs, video catalog)",
    "Content/demand gen: tech blogs, benchmark videos, webinar series",
    "Field marketing: on‑site factory demos with OEM/integrator"
  ]
} as const;

export default data;
