// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/en/hero.ts
const data = {
  "subtitle": "RaaS with robot app store, policy hub and <10ms edge – safe, auditable, scalable.",
  "title": "Humanoid Robotics as a Service – App store for skills"
} as const;

export default data;
