// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/en/impact.ts
const data = {
  "description": [
    "Our technology reduces implementation costs of robotics solutions by up to 70%, enabling broader access to automation.",
    "Through an open-source strategy, we foster innovation and collaboration in the robotics community."
  ],
  "socialImpact": [
    "Create high-skilled jobs in the tech sector",
    "Support educational institutions with free licenses",
    "Collaborate with non-profit organizations"
  ],
  "sustainabilityGoals": [
    "Reduce CO2 emissions via more efficient logistics",
    "Improve education access with affordable robotics",
    "Promote inclusion with accessible technologies"
  ],
  "title": "Impact & Sustainability"
} as const;

export default data;
