// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/en/kpi.ts
const data = {
  "activeSkills": "Active skills/robot",
  "adoption": "Skill adoption",
  "latency": "Edge latency",
  "roi": "ROI",
  "throughput": "Throughput",
  "units": "Units",
  "uptime": "Uptime"
} as const;

export default data;
