// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/en/mlops.ts
const data = {
  "practices": [
    "Model registry & reproducibility, rollback strategies",
    "A/B evals, shadow mode, data quality guards",
    "Security reviews & approval gates (four‑eyes principle)"
  ],
  "stack": [
    "Policy hub, versioning, feature flags, canary rollouts",
    "Telemetry pipelines (logs/traces/metrics) & observability",
    "CI/CD for models & skills incl. offline/online evals"
  ]
} as const;

export default data;
