// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/en/nav.ts
const data = {
  "brand": "SIGMACODE AI Robotics",
  "brandSubtitle": "Robotics",
  "brandTitle": "SIGMACODE AI",
  "downloadPdf": "Print to PDF",
  "homeAria": "{brand} – Home",
  "language": "Language",
  "mainNav": "Main navigation"
} as const;

export default data;
