// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/en/pitchCover.ts
const data = {
  "open": "Open pitch deck online",
  "subtitle": "Humanoid Robotics · App‑Store · AI Assistance · Scalable RaaS",
  "title": "Investor Pitch"
} as const;

export default data;
