// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/en/problem.ts
const data = {
  "defaults": {
    "empty": "No problems defined"
  },
  "overviewTitle": "Problem Overview",
  "title": "Problem"
} as const;

export default data;
