// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/en/responsibleAI.ts
const data = {
  "evals": [
    "Benchmark suites for perception/manipulation & safety metrics",
    "Latency/reliability tests with SLOs and canary comparisons"
  ],
  "provenance": [
    "Dataset lineage, versioning, model cards & data sheets",
    "Audit trails and release approval workflows"
  ],
  "redTeam": [
    "Scenario‑based stress tests (out‑of‑distribution, sensor failures)",
    "HRI edge cases and fail‑safe validation with human oversight"
  ]
} as const;

export default data;
