// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/en/risks.ts
const data = {
  "additional": {
    "Monitoring": "KPIs/telemetry, A/B evals, red teaming for safety/AI",
    "ThirdParties": "Contracts/SLAs, audit trails, pen tests"
  },
  "benefits": [
    "Faster certifications via reusable, verified modules",
    "Higher customer loyalty through measurable ROI and predictable rollouts",
    "Product quality through telemetry, end‑to‑end evals and fleet learning"
  ],
  "finance": {
    "cashflow": {
      "mitigation": "Hardware leasing/partners, staggered deliveries, prepayments/deposits, strict working‑capital monitoring.",
      "risk": "Upfront financing of hardware/prototypes, long sales cycle and capex can burden liquidity.",
      "title": "Cash flow"
    },
    "grants": {
      "mitigation": "Hybrid financing (seed + grants), milestone‑based use of funds, alternative programs (EU/co‑funding).",
      "risk": "Missing or delayed grant approvals strain the cash runway.",
      "title": "Grants"
    },
    "title": "Finance"
  },
  "list": [
    "Technology risk (TRL, sim‑to‑real, safety/HRI)",
    "Go‑to‑market (OEM/integrator reliance, certification cycles)",
    "Financing (hardware CAPEX, scaling costs)",
    "Compliance (EU AI Act, CE, cybersecurity/privacy)",
    "Talent (DeepTech, competition for experts)"
  ],
  "market": {
    "adoption": {
      "mitigation": "Design‑partner program, measurable pilot KPIs, training/enablement, pre‑built templates for common processes.",
      "risk": "Enterprise adoption may be delayed (change management, plant certification, internal compliance).",
      "title": "Adoption"
    },
    "competition": {
      "mitigation": "Differentiation via app store/SDK, certified third‑party skills, EU compliance & safety as market drivers, focus on high‑impact workflows.",
      "risk": "Strong competition from OEM stacks and horizontal platforms; price pressure on standard skills.",
      "title": "Competition"
    },
    "pricing": {
      "mitigation": "Tiered + usage model, ROI simulator, pay‑per‑outcome options and lean entry bundles (PoC packages).",
      "risk": "Limited willingness to pay for certain workflows or in early automation phases.",
      "title": "Pricing"
    },
    "title": "Market"
  },
  "mitigation": {
    "items": [
      "Milestone plan with evals & risk register (WP1–WP4)",
      "Partnerships (integrators/OEMs), design‑partner program",
      "Hybrid financing (seed + grants), cost control",
      "Provenance/evals, security program, compliance docs",
      "ESOP & branding, cooperation with universities/networks"
    ],
    "title": "Mitigation"
  },
  "mitigationDetailed": {
    "finance": [
      "Leasing/partnerships for CAPEX, prepayments/deposits",
      "Scenario planning and cost control, runway alerts",
      "Multi‑track grants and milestone gatekeeping"
    ],
    "legal": [
      "Early involvement of compliance/safety officers",
      "Standardized test/acceptance protocols, audit trails",
      "Contract SLAs and liability provisions with partners"
    ],
    "market": [
      "Design partners & references, repeatable pilot playbooks",
      "ROI simulators and clear business cases per workflow",
      "Communicate certification roadmaps (CE/AI Act)"
    ],
    "tech": [
      "Risk register per work package (WP1–WP4) with clear owners",
      "Canary rollouts, feature flags, gradual activation",
      "Evaluations/red teaming, formal constraints, simulated edge cases"
    ],
    "title": "Mitigation (detailed)"
  },
  "operations": {
    "keyPeople": {
      "mitigation": "Documentation, pairing/reviews, rotation, contingency plans and redundancy for critical roles.",
      "risk": "Dependence on key personnel increases failure/knowledge risks.",
      "title": "Key people"
    },
    "talent": {
      "mitigation": "ESOP & employer branding, remote‑friendly teams, university collaborations, targeted senior hires with multiplier effect.",
      "risk": "Scarcity of DeepTech profiles (robotics/controls/ML) limits execution speed.",
      "title": "Talent"
    },
    "title": "Operations"
  },
  "regulatory": {
    "cert": {
      "mitigation": "Standardized test plans, re‑use of certified modules, close collaboration with safety officers, pilot plants as references.",
      "risk": "On‑site acceptance (safety/HRI) varies by location and requires additional tests.",
      "title": "Certifications"
    },
    "eu": {
      "mitigation": "Early compliance management, risk/data/model governance, complete logs, model cards/datasheets and CE documentation.",
      "risk": "Misclassification or incomplete evidence can delay certification and rollouts.",
      "title": "EU/AI Act"
    },
    "title": "Regulatory"
  },
  "tech": {
    "aiSafety": {
      "mitigation": "Zone/contact‑force guardrails, formal constraints, red teaming & evaluations, human‑in‑the‑loop for risky maneuvers, audit trail & provenance.",
      "risk": "Misbehavior of learned policies under edge conditions (out‑of‑distribution, latency, sensor noise) can affect safety/HRI.",
      "title": "AI Safety"
    },
    "complexity": {
      "mitigation": "Phased plan with clear milestones (WP1–WP4), early end‑to‑end tests, canary rollouts, tele‑assist and robust observability (tracing/logs/metrics).",
      "risk": "Whole‑body manipulation, sim‑to‑real and safety increase system complexity and pose integration/stability risks.",
      "title": "Complexity"
    },
    "title": "Technology",
    "vendors": {
      "mitigation": "Abstraction layer (ROS2/hardware adapters), multi‑vendor qualification, long‑term SLAs and second‑source strategy.",
      "risk": "Dependence on hardware/cloud vendors can impact costs, lead times and roadmap.",
      "title": "Vendor dependence"
    }
  },
  "title": "Risks"
} as const;

export default data;
