// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/en/sections.ts
const data = {
  "appendix": "Appendix",
  "businessModel": "Business Model",
  "capTable": "Cap Table",
  "company": "Company",
  "compliance": "Compliance",
  "costPlan": "Cost Plan",
  "cta": "Next Steps",
  "dissemination": "Dissemination",
  "executive": "Executive Summary",
  "exit": "Exit Strategy",
  "finance": "Finance",
  "gtm": "Go-to-Market",
  "impact": "Impact & Sustainability",
  "innovation": "Innovation",
  "ipMoat": "IP & Moat",
  "market": "Market & Competition",
  "marketCompetitive": "Competitive Landscape",
  "operations": "Operations",
  "problem": "Problem",
  "products": "Products",
  "responsibleAI": "Responsible AI",
  "risks": "Risks",
  "solution": "Solution",
  "stateOfTheArt": "State of the Art",
  "team": "Team",
  "teamOrg": "Team & Organization",
  "technology": "Technology",
  "traction": "Traction & KPIs",
  "tractionKpis": "Traction & KPIs"
} as const;

export default data;
