// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/en/teamOrg.ts
const data = {
  "founders": [
    "Ismet Mesic – CIO & CTO",
    "Medina Mesic, MSc – Co‑CEO & CMO",
    "Atifa Mesic – CFO"
  ],
  "ftePlan": [
    {
      "focus": [
        "AI/robotics",
        "controls",
        "cloud"
      ],
      "roles": [
        "AI eng",
        "controls eng",
        "full‑stack",
        "PM"
      ],
      "teamSize": 6,
      "year": "Y1"
    },
    {
      "focus": [
        "safety",
        "SDK",
        "GTM"
      ],
      "roles": [
        "safety eng",
        "SDK eng",
        "solutions",
        "support"
      ],
      "teamSize": 10,
      "year": "Y2"
    }
  ],
  "summary": "Management: Medina & Atifa Mesic. Technology & innovation led by the CIO/CTO. Marketing & sales, finance & banking are clearly assigned. Focus: safe, auditable humanoid robotics with an app‑store ecosystem.",
  "years": [
    {
      "focus": [
        "AI/robotics",
        "controls",
        "cloud"
      ],
      "roles": [
        "AI eng",
        "controls eng",
        "full‑stack",
        "PM"
      ],
      "size": 6,
      "year": "Y1"
    },
    {
      "focus": [
        "safety",
        "SDK",
        "GTM"
      ],
      "roles": [
        "safety eng",
        "SDK eng",
        "solutions"
      ],
      "size": 10,
      "year": "Y2"
    }
  ]
} as const;

export default data;
