// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/en/workPackages.ts
const data = {
  "headers": [
    "WP",
    "Name",
    "Timeline",
    "Deliverables",
    "Budget (k€)"
  ],
  "rows": [
    {
      "budget": 18,
      "deliverables": [
        "Requirements",
        "Project plan",
        "Risk analysis"
      ],
      "id": "WP1",
      "name": "Project preparation & requirements",
      "timeline": "M0–M2"
    },
    {
      "budget": 32,
      "deliverables": [
        "Tech concept",
        "Architecture",
        "Interfaces"
      ],
      "id": "WP2",
      "name": "Technical concept & architecture",
      "timeline": "M3–M5"
    },
    {
      "budget": 110,
      "deliverables": [
        "Core features",
        "Tests",
        "Docs"
      ],
      "id": "WP3",
      "name": "Development & implementation",
      "timeline": "M6–M13"
    },
    {
      "budget": 42,
      "deliverables": [
        "Test reports",
        "Bug reports",
        "Release"
      ],
      "id": "WP4",
      "name": "Testing & QA",
      "timeline": "M11–M14"
    },
    {
      "budget": 20,
      "deliverables": [
        "Training",
        "User manual",
        "Final report"
      ],
      "id": "WP5",
      "name": "Rollout & training",
      "timeline": "M15–M16"
    }
  ],
  "title": "Work Packages & Budget (indicative)"
} as const;

export default data;
