// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/en/workPackagesDetailed.ts
const data = {
  "headersEffort": [
    "WP",
    "Role",
    "FTE"
  ],
  "items": [
    {
      "budget": {
        "material": 2,
        "other": 1,
        "personnel": 15,
        "subcontracting": 0
      },
      "budgetJustification": {
        "material": "Workshop materials, tools",
        "other": "Travel/communication",
        "personnel": "PM/PL for workshops and planning"
      },
      "deliverables": [
        "Requirements document",
        "Project plan",
        "Risk analysis"
      ],
      "dependencies": [],
      "effort": [
        {
          "fte": 0.6,
          "role": "Project lead"
        },
        {
          "fte": 0.4,
          "role": "Product manager"
        }
      ],
      "id": "WP1",
      "kpis": [
        "Scope coverage ≥ 90% (review checklist)",
        "Review iterations ≤ 2 until sign‑off"
      ],
      "milestones": [
        {
          "acceptance": "Stakeholder sign‑off",
          "label": "Kickoff",
          "month": 0
        },
        {
          "acceptance": "Review completed (all blockers resolved)",
          "label": "Requirements v1",
          "month": 1
        }
      ],
      "mitigations": [
        "Early reviews",
        "Asynchronous alignment"
      ],
      "name": "Project preparation & requirements analysis",
      "objectives": [
        "Goals and scope aligned with stakeholders",
        "Risks and assumptions documented"
      ],
      "personMonths": [
        {
          "pm": 1.8,
          "role": "Project lead"
        },
        {
          "pm": 1.2,
          "role": "Product manager"
        }
      ],
      "risks": [
        "Unclear requirements",
        "Stakeholder availability"
      ],
      "scope": [
        "Workshops, interview guides, documentation",
        "Project plan with milestones and sign‑offs"
      ],
      "timeframe": "Month 0–2",
      "trl": {
        "start": 2,
        "target": 3
      }
    },
    {
      "budget": {
        "material": 5,
        "other": 2,
        "personnel": 25,
        "subcontracting": 0
      },
      "budgetJustification": {
        "material": "Prototyping licenses/tools",
        "personnel": "Architecture/design work by multiple senior roles"
      },
      "deliverables": [
        "Technical concept",
        "System architecture",
        "Interface spec"
      ],
      "dependencies": [
        "WP1"
      ],
      "effort": [
        {
          "fte": 0.6,
          "role": "CIO/CTO"
        },
        {
          "fte": 0.8,
          "role": "Platform/Full‑stack"
        },
        {
          "fte": 0.6,
          "role": "Safety engineer"
        }
      ],
      "id": "WP2",
      "kpis": [
        "Architecture decisions ≤ 2 iterations (decision matrix)",
        "Interface spec ≥ 90% complete"
      ],
      "milestones": [
        {
          "acceptance": "Decision document approved (CTO + Safety)",
          "label": "Architecture review",
          "month": 3
        }
      ],
      "mitigations": [
        "Spike prototypes",
        "Decision matrix"
      ],
      "name": "Technical concept & architecture",
      "objectives": [
        "Target architecture and interfaces specified",
        "Make/Buy/Partner decisions"
      ],
      "personMonths": [
        {
          "pm": 1.8,
          "role": "CIO/CTO"
        },
        {
          "pm": 2.4,
          "role": "Platform/Full‑stack"
        },
        {
          "pm": 1.8,
          "role": "Safety engineer"
        }
      ],
      "risks": [
        "Delayed tech decisions"
      ],
      "scope": [
        "System architecture",
        "Interfaces/SDK",
        "Quality attributes"
      ],
      "timeframe": "Month 3–5",
      "trl": {
        "start": 3,
        "target": 4
      }
    },
    {
      "budget": {
        "material": 10,
        "other": 5,
        "personnel": 80,
        "subcontracting": 15
      },
      "budgetJustification": {
        "material": "Compute/cloud/tools",
        "other": "Licensing/misc costs",
        "personnel": "Main development phase (AI/FS/Controls/QA)",
        "subcontracting": "Specific 3rd‑party components/integrations"
      },
      "deliverables": [
        "Source code",
        "Test reports",
        "Documentation"
      ],
      "dependencies": [
        "WP2"
      ],
      "effort": [
        {
          "fte": 2.5,
          "role": "AI engineer"
        },
        {
          "fte": 2,
          "role": "Full‑stack engineer"
        },
        {
          "fte": 1,
          "role": "Controls engineer"
        },
        {
          "fte": 0.5,
          "role": "QA engineer"
        }
      ],
      "id": "WP3",
      "kpis": [
        "Velocity ≥ 20 SP/sprint (median across 4 sprints)",
        "Unit coverage ≥ 60% (core modules)",
        "E2E smoke suite < 10 min p95"
      ],
      "milestones": [
        {
          "acceptance": "Smoke tests green, public demo ready",
          "label": "MVP feature set",
          "month": 8
        }
      ],
      "mitigations": [
        "Scope cut criteria",
        "Integration test stubs"
      ],
      "name": "Development & implementation",
      "objectives": [
        "MVP functionality delivered",
        "CI/CD, observability, security gates active"
      ],
      "personMonths": [
        {
          "pm": 20,
          "role": "AI engineer"
        },
        {
          "pm": 16,
          "role": "Full‑stack engineer"
        },
        {
          "pm": 8,
          "role": "Controls engineer"
        },
        {
          "pm": 4,
          "role": "QA engineer"
        }
      ],
      "risks": [
        "Feature creep",
        "3rd‑party integration"
      ],
      "scope": [
        "Core features",
        "Testing",
        "Documentation"
      ],
      "timeframe": "Month 6–13",
      "trl": {
        "start": 4,
        "target": 6
      }
    },
    {
      "budget": {
        "material": 5,
        "other": 2,
        "personnel": 30,
        "subcontracting": 5
      },
      "budgetJustification": {
        "material": "Test environment/tools",
        "personnel": "QA/SRE efforts for quality & stability",
        "subcontracting": "External audits/tests (if required)"
      },
      "deliverables": [
        "Test reports",
        "Bug reports",
        "Release documentation"
      ],
      "dependencies": [
        "WP3"
      ],
      "effort": [
        {
          "fte": 1.5,
          "role": "QA engineer"
        },
        {
          "fte": 0.5,
          "role": "SRE/MLOps"
        }
      ],
      "id": "WP4",
      "kpis": [
        "Defect leakage < 3% (staging→prod)",
        "MTTR < 1 day (p95)",
        "Reliability score ≥ 0.98"
      ],
      "milestones": [
        {
          "acceptance": "CI coverage ≥ 70% (core flows)",
          "label": "Coverage 70%",
          "month": 12
        }
      ],
      "mitigations": [
        "Canary/chaos tests",
        "Isolated pipelines"
      ],
      "name": "Testing & quality assurance",
      "objectives": [
        "Quality evidenced",
        "Release criteria met"
      ],
      "personMonths": [
        {
          "pm": 6,
          "role": "QA engineer"
        },
        {
          "pm": 2,
          "role": "SRE/MLOps"
        }
      ],
      "risks": [
        "Unstable test environment"
      ],
      "scope": [
        "System tests",
        "Safety checks",
        "Release docs"
      ],
      "timeframe": "Month 11–14",
      "trl": {
        "start": 6,
        "target": 7
      }
    },
    {
      "budget": {
        "material": 3,
        "other": 2,
        "personnel": 15,
        "subcontracting": 0
      },
      "budgetJustification": {
        "material": "Enablement materials",
        "other": "Travel/support",
        "personnel": "Training/rollout"
      },
      "deliverables": [
        "Training materials",
        "User manual",
        "Final report"
      ],
      "dependencies": [
        "WP4"
      ],
      "effort": [
        {
          "fte": 0.5,
          "role": "Project lead"
        },
        {
          "fte": 1,
          "role": "Solutions engineer"
        }
      ],
      "id": "WP5",
      "kpis": [
        "NPS ≥ 30",
        ">= 2 reference customers with written statement",
        "Onboarding time ≤ 1 day/customer"
      ],
      "milestones": [
        {
          "acceptance": "Stakeholder acceptance (SLA agreed)",
          "label": "Go‑live",
          "month": 15
        }
      ],
      "mitigations": [
        "Enablement plan",
        "Support SLAs"
      ],
      "name": "Rollout & training",
      "objectives": [
        "Go‑live",
        "User adoption/training"
      ],
      "personMonths": [
        {
          "pm": 1,
          "role": "Project lead"
        },
        {
          "pm": 2,
          "role": "Solutions engineer"
        }
      ],
      "risks": [
        "Low adoption"
      ],
      "scope": [
        "Training",
        "User manual",
        "Final report"
      ],
      "timeframe": "Month 15–16",
      "trl": {
        "start": 7,
        "target": 8
      }
    }
  ],
  "note": "Structure: Objectives/Scope, Deliverables, Effort (FTE), Dependencies, Risks, KPIs, Milestones, Budget",
  "title": "Work Packages – Detailed (AWS/FFG‑compliant)"
} as const;

export default data;
