// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/de/businessModel.ts
const data = {
  "description": [
    "Monetarisierung über RaaS‑Subscription, App‑Store‑Ökosystem, Custom Development und perspektivisch White‑Label‑Plattformen."
  ],
  "kpi": {
    "arpu": "€3.0k–€4.0k / Roboter / Monat",
    "cac": "€4k–€8k",
    "grossMargin": "62–68%",
    "ltv": "€40k–€60k"
  },
  "partnerships": [
    "OEM‑Partnerschaften (Robotik‑Hersteller) für Bundles & Zertifizierungen",
    "Systemintegratoren für Rollout, Schulung und Wartung vor Ort",
    "Cloud‑/Edge‑Infrastruktur (AWS/GCP) – Security, Observability, Marketplaces",
    "Content/SDK‑Partner – ROS2, Tooling, Safety‑/Policy‑Module",
    "Forschung/Universitäten für RL‑Modelle, Safety‑Evaluations, Talentpipeline"
  ],
  "pricing": [
    "Freemium (limitiert) • Basic €29 • Pro €99 • Enterprise ab €299",
    "Rabatte: 10% Jahresabonnement, 15% Non‑Profits, 25% Bildungseinrichtungen"
  ],
  "revenueStreams": [
    {
      "description": "Monatliche Nutzungspauschale je Roboter inkl. Hardware, Software‑Lizenz, Wartung/Updates & Support (SLA‑gestaffelt). Preisrange je Roboter: 3.000–4.000 € pro Monat.",
      "type": "RaaS‑Subscription"
    },
    {
      "description": "Revenue‑Share: Plattform 30% / Entwickler 70% (Enterprise: 15% / 85%). Erwartetes Volumen: 5–15% des Gesamtumsatzes ab Jahr 3.",
      "type": "App‑Store‑Beteiligung"
    }
  ],
  "salesChannels": [
    "Direktvertrieb (Inbound/Outbound) – Demo‑Flows, Self‑Serve‑Onboarding",
    "Partner/Integrator‑Netzwerk – OEMs, Systemintegratoren, regionale Reseller",
    "Developer‑Ökosystem – App‑Store, Community, Referenzen/Showcases",
    "Enterprise‑Co‑Selling – Cloud‑Marketplaces, Rahmenverträge",
    "Events/Webinare – vertikalspezifische Use‑Cases, Design‑Partner‑Programme"
  ],
  "unitEconomics": [
    "RaaS‑Preis je Roboter: 3.000–4.000 € / Monat (Ø ~3.500 €)",
    "Deckungsbeitrag je Roboter/Monat: ~2.000–2.400 € nach COGS (Hardware, Connectivity, Support)",
    "Payback CAC: ~3 Monate (bei ~2.100 € mtl. Beitrag, CAC ~6.000 €)",
    "LTV (Beitrag) ~50.000 € bei 24 Monaten Bindung; LTV/CAC > 7x",
    "Zusatz‑ARPU (User) ~€49 für Software/Services; Upside durch App‑Käufe",
    "Bruttomarge 62–68% (Software‑/Plattformanteil steigend)"
  ],
  "valueProp": [
    "RaaS (Robots-as-a-Service) – geringe Einstiegskosten, planbare OPEX",
    "Plattform-Ökosystem mit App‑Store – Skills und Charaktere wie Apps",
    "SigmaCode AI – Cloud/Edge‑Agenten orchestrieren sichere, auditierbare Workflows",
    "Schnelle Integration (ROS2/SDK), Enterprise‑Security & Compliance (EU AI Act/DSGVO)"
  ]
} as const;

export default data;
