// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/de/chapters.ts
const data = {
  "businessModel": {
    "grantFitTitle": "Grant Fit (AWS / FFG)",
    "gtmTitle": "Go‑To‑Market & Piloten",
    "moatTitle": "IP & Technischer Moat",
    "overviewTitle": "Überblick",
    "subtitle": "Geschäftsmodell & Monetarisierung"
  },
  "compliance": {
    "subtitle": "Compliance & Responsible AI"
  },
  "cover": {
    "title": "Deckblatt"
  },
  "executive": {
    "subtitle": "Kurzüberblick & Key Facts"
  },
  "executiveSummary": {
    "paragraphs": [
      "Wertangebot: Humanoide AI‑Robotik als RaaS mit Robot‑App‑Store und Policy‑Hub – zertifizierte Skills werden zu End‑to‑End‑Workflows komponiert, sicher ausgerollt (CE/AI‑Act) und fleet‑weit überwacht.",
      "Traktion/KPIs: Pilotflotte (Logistik/Fertigung) in Vorbereitung, App‑Store‑Beta, Ziel‑KPIs >99.99% Uptime, <10ms Edge‑Reaktion, >60% Skill‑Adoption je Kunde in 6 Monaten.",
      "Finanzierungs‑Ask: Seed + Grants für Team, Safety‑Evidenzen und Pilotflotte; Mittelverwendung: R&D/Safety, App‑Store/SDK, GTM‑Partnerschaften, Compliance/CE‑Doku."
    ],
    "sections": {
      "businessModel": {
        "content": "RaaS (Subscription + Usage) + Skill‑Lizenzen + Marketplace‑Fee. Enterprise‑Rollouts mit Service‑ und Support‑Plänen.",
        "title": "Geschäftsmodell"
      },
      "market": {
        "content": "Megatrend Automatisierung/Reshoring. TAM >$40B bis 2030 (Service Robotics & Humanoids). Starke Nachfrage in Logistik, Fertigung, Facility & Service.",
        "title": "Markt"
      },
      "problem": {
        "content": "Akuter Fachkräftemangel, gefährliche/monotone Aufgaben und fragmentierte IT/OT‑Stacks bremsen die Produktivität. Klassische Automatisierung ist unflexibel, teuer in der Anpassung und skaliert schlecht über Standorte und Use‑Cases.",
        "title": "Problem"
      },
      "solution": {
        "platform": {
          "content": "Humanoide AI‑Robotik als RaaS mit Robot‑App‑Store: zertifizierte Skills (Greifen, Navigation, Inspektion, Handling) werden zu End‑to‑End‑Workflows komponiert und fleet‑weit ausgerollt.",
          "title": "Plattform"
        },
        "technology": {
          "content": "Perzeption (Multi‑Sensor/VLM/3D), Decision (Planner/Policies/Safety), Execution (Force/Impedance). RL/IL‑Agenten lernen aus Demos & Simulation; Policy‑Hub, Tele‑Assist, Fleet‑Learning, CE/AI‑Act‑Compliance.",
          "title": "Technologie"
        },
        "title": "Lösung"
      },
      "usps": {
        "items": [
          "Robot‑App‑Store: schnelle Time‑to‑Value, modulare Skills, vendor‑neutral",
          "Policy‑Hub & Safety‑Guardrails: deterministische, auditierbare Ausführung",
          "Fleet‑Learning: kontinuierliche Performance‑Zuwächse (RL/IL)",
          "99.99% Uptime, <10ms Edge‑Reaktion, Zero‑Downtime‑Updates",
          "Enterprise‑Integration (ERP/WMS/MES/IoT, Digital Twins)"
        ],
        "title": "USPs"
      }
    },
    "title": "Executive Summary"
  },
  "finance": {
    "subtitle": "Finanzen & KPIs"
  },
  "impact": {
    "subtitle": "Impact & Nachhaltigkeit"
  },
  "market": {
    "subtitle": "Markt & Wettbewerb"
  },
  "products": {
    "subtitle": "Produkte & Roadmap"
  },
  "risks": {
    "subtitle": "Risiken & Mitigation"
  },
  "team": {
    "subtitle": "Team & Organisation"
  },
  "technology": {
    "subtitle": "Technologie & Architektur"
  }
} as const;

export default data;
