// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/de/closingPage.ts
const data = {
  "legal": "Vertraulich – ausschließlich für Evaluationszwecke bestimmt.",
  "next": {
    "title": "Vorschlag nächster Schritt"
  },
  "prepared": "Vorbereitet am",
  "qr": {
    "desc": "Scannen Sie den QR, um die Live‑Version aufzurufen oder einen Termin zu vereinbaren."
  },
  "subtitle": "Vielen Dank für Ihr Interesse – wir freuen uns auf das Gespräch.",
  "title": "Kontakt & Nächste Schritte"
} as const;

export default data;
