// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/de/company.ts
const data = {
  "industry": "Humanoide Robotik / AI‑Software / Industrial Automation",
  "legal": {
    "entity": "GmbH i.G.",
    "founding": "2025",
    "hq": "Wien"
  },
  "location": "Wien, AT",
  "milestones": [
    "PoC in Logistik/Fertigung",
    "Pilotflotte mit Policy‑Hub und Tele‑Assist",
    "Robot App‑Store (erste Skills) live"
  ],
  "mission": "Physische Arbeit sicher, flexibel und skalierbar machen – Software‑First, auditierbar und enterprise‑ready",
  "name": "Humanoid Robotics Platform GmbH (Arbeitstitel)",
  "team": "Core‑Team: AI/Robotics, Controls, Cloud, Product",
  "vision": "Führende humanoide AI‑Robotik‑Plattform mit Robot‑App‑Store für die Industrie"
} as const;

export default data;
