// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/de/compliance.ts
const data = {
  "aiAct": [
    "Risikomanagement, Logging/Audits, Human Oversight, Model Cards"
  ],
  "aws": [
    "Vorgaben für sichere Cloud‑Architektur, Verschlüsselung, Monitoring"
  ],
  "privacy": [
    "DSGVO‑konforme Datenflüsse, Datenminimierung, Edge‑Inference"
  ],
  "safety": [
    "Zonen/Kontaktkraft‑Limits, HRI‑Risikobeurteilung, Fail‑Safe"
  ],
  "safetyStandards": [
    "CE, ISO 10218/TS 15066, ISO 13482"
  ],
  "securityProgram": [
    "Zero‑Trust, Secrets‑Management, Pen‑Tests, Threat‑Modeling"
  ]
} as const;

export default data;
