// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/de/content.ts
const data = {
  "company": {
    "industry": "AI‑Robotik / Software",
    "location": "München, Deutschland",
    "mission": "Roboterfähigkeiten als Apps – sicher, auditierbar, skalierbar",
    "name": "SIGMACODE AI GmbH",
    "team": "Kernteam 6 FTE, Hiring‑Fokus AI/Robotics",
    "vision": "Humanoide AI‑Robotik, die Arbeit sicherer und produktiver macht"
  },
  "market": {
    "sam": "Industrie‑Segmente mit hohem Bedarf: Logistik, Fertigung, Facility & Service – initiale Fokuskorridore mit klarer Zahlungsbereitschaft.",
    "som": "Pilot‑regionen mit Enterprise‑Rollouts (DACH/EU) und Partner‑Ökosystem – skalierbar über App‑Store und Fleet‑Deployments.",
    "tam": "> $40 Mrd. bis 2030 (Service Robotics & Humanoids) – getrieben durch Automatisierung, Reshoring und demografischen Wandel."
  },
  "solution": {
    "agents": "RL/IL‑Agenten: Lernen aus Demos & Simulation (Policy‑Hub)",
    "appstore": "Robot‑App‑Store: zertifizierte Skills, Marketplace & Billing",
    "integration": "Enterprise‑Integration: ERP/WMS/MES/IoT, Digital Twins",
    "rass": "Robot‑as‑a‑Service: Subscription + Usage mit Fleet‑Management",
    "usp": "Guardrails & Compliance (CE/AI‑Act), Zero‑Downtime‑Deployments"
  }
} as const;

export default data;
