// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/de/coverPage.ts
const data = {
  "companyName": "Investoren & Förderstellen",
  "confidentialNotice": "Vertraulich – ausschließlich für Evaluierungszwecke. Weitergabe nur mit Zustimmung von SIGMACODE AI Robotics.",
  "confidential": "Vertraulich & urheberrechtlich geschützt. Dieses Dokument enthält proprietäre Informationen und ist ausschließlich für die adressierten Empfänger bestimmt. Eine Weitergabe, Vervielfältigung oder Veröffentlichung – vollständig oder in Teilen – ist ohne vorherige schriftliche Zustimmung untersagt.",
  "cta": {
    "goToChapterOne": "Weiter zu Kapitel 1"
  },
  "date": "Datum",
  "openPitch": "Pitch‑Deck öffnen",
  "preparedFor": "Vorbereitet für",
  "versionLabel": "Version",
  "version": "v1.0",
  "subtitle": "Unsere Plattform vereint Hardware, KI und ein kuratiertes App‑Ökosystem zu alltagstauglicher humanoider Assistenz – mit klarem Branchenfokus auf Logistik, Fertigung und Facility. Modulare Skills, nahtlose Over‑the‑Air‑Updates und ein Developer‑Store ermöglichen schnelle Wertschöpfung, skalierbare Rollouts und messbaren ROI. Sicherheit und Datenschutz sind Grundprinzip (Security by Design, Privacy‑first); der Pfad zu CE‑Konformität und EU AI Act ist integraler Bestandteil.",
  "title": "Humanoide Robotik as a Service",
  "contact": {
    "title": "Kontakt",
    "person": "Ansprechpartner",
    "personName": "Michael S. (Managing Director)",
    "email": "E‑Mail",
    "emailAddress": "contact@sigmacode.ai",
    "phone": "Telefon",
    "phoneNumber": "+43 660 0000000",
    "address": "Adresse",
    "addressValue": "SIGMACODE AI Robotics · Wien, Österreich"
  },
  "value": {
    "aas": "Agents as a Service · Aufgaben statt Apps",
    "appstore": "Kuratiertes KI‑App‑Ökosystem · Developer‑Store",
    "humanoid": "Humanoide Robotik · praxisnah & sicher"
  }
} as const;

export default data;
