// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/de/cv.ts
const data = {
  "actionsLabel": "CV Aktionen",
  "availability": "Verfügbar: Teilzeit · Projektbasis",
  "backToPlan": "Zurück zum Businessplan",
  "contact": {
    "copied": "Kopiert",
    "copyEmail": "E-Mail kopieren",
    "copyEmailAria": "E-Mail-Adresse kopieren",
    "email": "ismet@mesic.dev",
    "github": "",
    "label": "Kontakt",
    "linkedin": "",
    "open": "Öffnen:"
  },
  "details": "Details",
  "fallback": [
    {
      "bullets": [
        "—",
        "—"
      ],
      "period": "2021–Heute",
      "subtitle": "—",
      "title": "Senior Executive"
    },
    {
      "bullets": [
        "—"
      ],
      "period": "2018–2021",
      "subtitle": "—",
      "title": "Executive"
    }
  ],
  "items": [
    {
      "bullets": [
        "Übernahme der Z-Line Automotive mit 10,4 Mio. € Schulden",
        "Sanierung und Sicherung von 150 Arbeitsplätzen",
        "Mit 1,2 Mio. € Startkapital Neugründung von Cutting Edge d.o.o.",
        "Firmenwertaufbau auf 10,5 Mio. € durch neue Auftragslage und Investoren",
        "Gewinnung neuer Gesellschafter: Recaro Automotive (20 %), Gruppo Mastrotto (15 %; 1,5 Mio. €)"
      ],
      "period": "05/2022 – 02/2024",
      "subtitle": "Z-Line Automotive (Slowenien) → Cutting Edge d.o.o.",
      "title": "Sanierer & Geschäftsführer"
    },
    {
      "bullets": [
        "Aufbau eines internationalen Handelsunternehmens für Medizinprodukte (Österreich, Deutschland, Slowakei, Skandinavien)",
        "Seit 2021 staatlich gelisteter Beschaffungspartner",
        "Skalierung der Firma im Bereich Medizintechnik & Beschaffung",
        "Übergabe des Unternehmens, um Fokus auf Robotics & AI zu legen"
      ],
      "period": "05/2020 – 02/2022",
      "subtitle": "Servacon GmbH",
      "title": "Geschäftsführer & Gesellschafter"
    },
    {
      "bullets": [
        "Aufbau und Leitung eines Covid-PCR-Testlabors",
        "Entwicklung & Umsetzung der Teststrategie während der Pandemie",
        "Koordination mit Behörden (B&B und B&C)"
      ],
      "period": "01/2022 – 06/2023",
      "subtitle": "PCR-Labor Kuhn & Mather OG",
      "title": "Leiter & Mitgründer"
    },
    {
      "bullets": [
        "Sachverständiger Software‑Audit der \"ApoSys\"‑Systemlandschaft (laufendes Server‑Softwaresystem)",
        "Fehlerquellenanalyse, Architektur‑/Performance‑Review, Betrieb & Monitoring",
        "Aufbau und Betreuung des Apotheken‑Online‑Shops sowie Prozess‑/Compliance‑Optimierung",
        "Sanierungsunterstützung als externer Experte (Vor‑Insolvenzphase, Stabilisierung & Maßnahmenplan)"
      ],
      "period": "08/2022 – 05/2023",
      "subtitle": "MediStore.at",
      "title": "Strategischer Berater & IT‑Audit"
    },
    {
      "bullets": [
        "Zusammenfassung: Kryptoberatung, Handel, GPU‑Mining (Luleå/SE) & Miningfarm (Priboj/RS)",
        "Rollen: Gründer/Geschäftsführer, Gesellschafter, Betreiber; Investitionsvolumen > 2,6 Mio. €"
      ],
      "period": "2016 – 2020",
      "subtitle": "Übersicht",
      "title": "Krypto & Mining"
    },
    {
      "bullets": [
        "Kryptoberatungsfirma; Aufbau von Beratungs- und Compliance-Services (keine Spekulationen)",
        "Erzielter Gewinn: ca. 800.000 € (2017–2019)",
        "Kundenfokus: KMU, High-Net-Worth & Early Adopters"
      ],
      "period": "2017 – 2020",
      "subtitle": "mscinvest d.o.o.",
      "title": "Gründer & Geschäftsführer"
    },
    {
      "bullets": [
        "Gesellschafter & Mitbetreiber",
        "Internationaler Kryptowährungshandel (OTC, EU/CZ/CEE)",
        "Operationales Risikomanagement & Banken-/Exchange-Schnittstellen"
      ],
      "period": "2017 – 2019",
      "subtitle": "coin2cash s.r.o.",
      "title": "Gesellschafter"
    },
    {
      "bullets": [
        "Betrieb einer GPU-Miningfarm in Luleå (SE)",
        "Grafikkartenvolumen: ~2 Mio. € Investment",
        "Infrastruktur & Energie-Optimierung für 24/7‑Betrieb"
      ],
      "period": "2016 – 2018",
      "subtitle": "bitunity GmbH – GPU‑Miningfarm Luleå (Schweden)",
      "title": "Gesellschafter & Mentor"
    },
    {
      "bullets": [
        "Aufbau einer Miningfarm in Priboj (Serbien)",
        "Investitionsvolumen: ~600.000 €",
        "Betrieb & Wartung, Sicherheits- und Kühlkonzept"
      ],
      "period": "2018 – 2019",
      "subtitle": "Miningfarm – Priboj (Serbien)",
      "title": "Betreiber"
    },
    {
      "bullets": [
        "Aufbau einer nachhaltigen GPU-basierten Mini-Plattform",
        "Frühe Infrastruktur zur Vorbereitung moderner KI-Anwendungen",
        "Mitarbeiterzahl: 5",
        "GPU‑Volumen: ~2 Mio. €"
      ],
      "period": "2016 – 2018",
      "subtitle": "GPU-Plattform Luleå (Schweden)",
      "title": "Gründer & Betreiber"
    },
    {
      "bullets": [
        "Entwicklung von Blockchain-Lösungen, Smart Contracts und Web3-Projekten",
        "Frühe Forschung im Bereich Dezentralisierung und Digital Assets"
      ],
      "period": "ab 2014",
      "subtitle": "Blockchain-Entwicklung",
      "title": "Softwareentwickler & Innovator"
    },
    {
      "bullets": [
        "Aufbau und Leitung eines Apple Stores mit Standorten im 13. und 9. Wiener Gemeindebezirk",
        "Zertifizierter Apple-Techniker und offizieller Apple-Servicepartner",
        "Verantwortung für Verkauf, Service und Mitarbeiterführung",
        "Mitarbeiterzahl: bis zu 15",
        "Wachstum: Skalierung von ~2.25x pro Standort; nach Eröffnung der zweiten Filiale gesamt ~4x Umsatzleistung (ohne Geldbeträge)"
      ],
      "period": "2010 – 2022",
      "subtitle": "Mac Plus Multimedia",
      "title": "Gründer & Geschäftsführer"
    },
    {
      "bullets": [
        "Gründung eines IT-Dienstleistungsunternehmens im Alter von 14 Jahren",
        "Computer- und Netzwerksupport für Privat- und Geschäftskunden",
        "Mitarbeiterzahl: 1 (Selbstständig)"
      ],
      "period": "2008 – 2010",
      "subtitle": "Computernotruf.at",
      "title": "Gründer & Geschäftsführer"
    },
    {
      "bullets": [
        "Gründung und Leitung einer White-Hat Hackergruppe",
        "Zusammenarbeit mit dem Anonymous-Kollektiv in internationalen Security-Projekten",
        "Fokus auf IT-Security, Netzwerksicherheit & Ethical Hacking"
      ],
      "period": "2004 – 2008",
      "subtitle": "ISA (International Security Alliance) – White-Hat Hacker Crew",
      "title": "Gründung und Leitung"
    },
    {
      "bullets": [
        "Aufbau einer Forenplattform mit mehr als 20.000 registrierten Usern",
        "Frühe Community- und Plattform-Entwicklung im Social-Media-Umfeld"
      ],
      "period": "2004 – 2006",
      "subtitle": "msn-icq-board.com",
      "title": "Gründer & Betreiber"
    },
    {
      "bullets": [
        "Leitung und strategische Weiterentwicklung von Vereinen zur Förderung von Forschung & Innovation",
        "Aufbau internationaler Netzwerke zwischen Wissenschaft, Technologie und Industrie"
      ],
      "period": "2021 – heute",
      "subtitle": "Forschungs- & Innovationsvereine (u. a. RCIID, Metanetwork)",
      "title": "Präsident"
    },
    {
      "bullets": [
        "Begleitung und Coaching mehrerer innovativer Startups",
        "Unterstützung in der Early-Adopter-Phase, u. a. Socialswap.io"
      ],
      "period": "2016 – heute",
      "subtitle": "Early-Bird-Projekte",
      "title": "Coach & Mentor"
    },
    {
      "bullets": [
        "Mitorganisation und strategische Begleitung einer österreichweiten MMA-Veranstaltung",
        "Mentoring von Athleten & Business-Partnern"
      ],
      "period": "2020 – heute",
      "subtitle": "Sparta CF (MMA Österreich)",
      "title": "Veranstalter & Strategischer Partner/Mentor"
    },
    {
      "bullets": [
        "Entwicklung innovativer Projekte in den Bereichen KI, Robotik und Digitalisierung",
        "Autor des Buches „#Sigmacode – Das mentale Betriebssystem für Männer“"
      ],
      "period": "2022 – heute",
      "subtitle": "Weitere Projekte & Engagements",
      "title": "Projektentwicklung"
    },
    {
      "bullets": [
        "Zusammenarbeit mit der Polizei bei der Aufklärung von Cyberkriminalität und digitalen Straftaten",
        "Anwendung von IT-Forensik und Hacker-Know-how für Ermittlungszwecke",
        "Datenanalyse und statistische Aufbereitung komplexer Aktenbestände",
        "Unterstützung von Rechtsanwälten durch präzise Datenaufbereitung, Referenzierung und Fallvorbereitung",
        "Aktiv in mehreren laufenden Fällen (2022 – heute)"
      ],
      "period": "Laufend",
      "subtitle": "Zusammenarbeit mit Polizei & Rechtsanwälten",
      "title": "IT-Security, Forensik & Legal Data Analytics"
    }
  ],
  "languages": {
    "items": [
      {
        "level": "Muttersprache",
        "name": "Deutsch"
      },
      {
        "level": "Muttersprache",
        "name": "Bosnisch"
      },
      {
        "level": "Fließend",
        "name": "Englisch"
      }
    ],
    "title": "Sprachen"
  },
  "less": "Weniger zeigen",
  "location": "Wien, AT",
  "metrics": {
    "experience": "Erfahrung",
    "experienceValue": "20+ Jahre",
    "focus": "Fokus",
    "focusValue": "AI, Robotics, Sanierung",
    "stack": "Stack",
    "stackValue": "AI • Robotics • Python • Cloud • Web3"
  },
  "more": "Mehr anzeigen",
  "noDetails": "Keine Details verfügbar",
  "openFullView": "Vollansicht öffnen",
  "pageSubtitle": "Executive – Unternehmer, Innovator, Sanierer, Mentor & Forscher",
  "pageTitle": "Lebenslauf Ismet Mesic",
  "performance": {
    "items": [
      {
        "company": "Cutting Edge d.o.o.",
        "description": "Sanierung und Neuaufstellung: von 1,2 Mio. € Startkapital zu 10,5 Mio. € Firmenwert (ROI: +775%)",
        "growth": 775,
        "period": "05/2022 – 02/2024",
        "value": 10.5,
        "startCapital": 1.2
      },
      {
        "company": "PCR-Labor Kuhn & Mather OG",
        "description": "Aufbau & Leitung eines PCR-Labors; Startkapital 0,25 Mio. €, Ergebnis: ca. 2,2 Mio. € Gewinn (ROI: +880%)",
        "growth": 880,
        "period": "01/2022 – 06/2023",
        "value": 2.2,
        "startCapital": 0.25
      },
      {
        "company": "Servacon GmbH",
        "description": "Aufbau und Skalierung im Medizintechnik-Bereich (DACH + Skandinavien); Startkapital 0,6 Mio. €, Ergebnis: 2,8 Mio. € Gewinn",
        "employees": 25,
        "growth": 280,
        "period": "05/2020 – 02/2022",
        "value": 2.8,
        "startCapital": 0.6
      },
      {
        "company": "Multiple Projekte",
        "description": "Diverse IT-Security und Blockchain Projekte mit internationalem Fokus",
        "employees": 12,
        "growth": 150,
        "period": "2018 – 2020",
        "value": 1.5
      },
      {
        "company": "IT-Security & Forensik",
        "description": "Aufbau von Security-Infrastrukturen und Forensik-Expertise",
        "employees": 8,
        "growth": 120,
        "period": "2015 – 2018",
        "value": 0.8
      },
      {
        "company": "Sparta CF (MMA Österreich)",
        "description": "Eventreihe professionalisiert, Sponsoring & Ticketing ausgebaut",
        "employees": 10,
        "growth": 95,
        "period": "2021 – heute",
        "value": 0.35
      },
      {
        "company": "Miss Germany Organization",
        "description": "Business- & Medienkooperationen, Reichweite und Partnerships skaliert",
        "employees": 20,
        "growth": 60,
        "period": "2019 – 2021",
        "value": 1.2
      },
      {
        "company": "Global Forensic Alliance",
        "description": "Aufbau einer internationalen Forensik-Community und Services",
        "employees": 9,
        "growth": 85,
        "period": "2017 – 2019",
        "value": 0.9
      }
      ,
      {
        "company": "Mac Plus Multimedia",
        "description": "Retail-Skalierung: von Basiswert auf ~2.25x pro Filiale; mit zweiter Filiale gesamt ~4x Wachstum (ohne Geldbeträge)",
        "growth": 300,
        "period": "2010 – 2022",
        "series": [1, 2.25, 4.0]
      },
      {
        "company": "mscinvest d.o.o.",
        "description": "Kryptoberatung; erwirtschafteter Gewinn ~0,8 Mio. € (keine Kursgewinne/Spekulationen)",
        "growth": 100,
        "period": "2017 – 2020",
        "value": 0.8
      },
      {
        "company": "coin2cash s.r.o.",
        "description": "Gesellschafter; internationaler OTC‑Handel mit Kryptowährungen",
        "growth": 100,
        "period": "2017 – 2019",
        "value": 0.5
      },
      {
        "company": "bitunity GmbH – Luleå (SE)",
        "description": "GPU‑Miningfarm; Investitionsvolumen ~2,0 Mio. €",
        "growth": 100,
        "period": "2016 – 2018",
        "value": 2.0
      },
      {
        "company": "Miningfarm Priboj (Serbien)",
        "description": "Miningfarm‑Betrieb; Investitionsvolumen ~0,6 Mio. €",
        "growth": 100,
        "period": "2018 – 2019",
        "value": 0.6
      }
    ],
    "title": "Erfolgsbilanz"
  },
  "period": "Zeitraum",
  "photo": "/cv/profile.jpg",
  "print": "Drucken",
  "printDescription": "Druckt die aktuelle Seite und speichert sie als PDF",
  "role": "Executive Entrepreneur & Innovation Architect",
  "saveAsPdf": "Als PDF speichern",
  "skills": {
    "categories": [
      {
        "items": [
          "Programmiererfahrung seit dem 12. Lebensjahr",
          "Python, Blockchain, Web, GPU, KI",
          "Apple-Technologie (zertifizierter Apple-Techniker)"
        ],
        "name": "Technologie"
      },
      {
        "items": [
          "Unternehmenssanierung (bis 150 Mitarbeiter)",
          "Firmenwerte bis zweistelliger Mio.-Bereich",
          "Business Development & internationale Kooperationen"
        ],
        "name": "Unternehmertum"
      },
      {
        "items": [
          "Medizintechnik & staatliche Beschaffung",
          "IT-Security & Forensik",
          "Strategische Logistikplanung & Supply Chain Management"
        ],
        "name": "Industrieerfahrung"
      },
      {
        "items": [
          "Coaching & Mentoring von Startups & Projekten",
          "Eventorganisation (Sport & Business)",
          "Community-Management (20.000+ User-Plattform)"
        ],
        "name": "Leadership"
      }
    ],
    "title": "Kenntnisse & Fähigkeiten"
  },
  "summary": {
    "bullets": [
      "Sanierung & Skalierung: Turnaround-Leader (150+ Mitarbeiter gesichert, Firmenwert > €10 Mio.)",
      "Technologie: AI & Robotik, Cloud/Edge, Safety – Fokus auf auditierbare Systeme",
      "Produkt: App‑Store/SDK, Partner‑Ökosystem, Developer‑Enablement",
      "Autor: #Sigmacode – Das mentale Betriebssystem für Männer",
      "Leadership & Netzwerk: Coaching/Mentoring, internationale Kooperationen",
      "FinOps & ROI: Effizienz, Kostenkontrolle, nachhaltige Profitabilität"
    ],
    "title": "Executive Summary"
  },
  "title": "Lebenslauf",
  "viewFull": "Lebenslauf vollständig ansehen",
  "workMode": "Remote‑first | DACH"
} as const;

export default data;
