// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/de/exit.ts
const data = {
  "buyers": {
    "financial": [
      "Growth-Equity-Fonds",
      "Sektorfokussierte PE"
    ],
    "strategic": [
      "Odds-Plattformen",
      "Datenanbieter",
      "Sportmedien",
      "US-Sportsbooks"
    ],
    "title": "Potenzielle Käufer"
  },
  "coInvest": {
    "points": [
      "Strategisches Co-Invest mit GTM-Partnern",
      "Syndiziertes SPV für strategische Käufer"
    ],
    "title": "Co‑Investment-Strukturen"
  },
  "earnOut": {
    "mechanics": [
      "Leistungsbasierte Tranchen (ARR-/EBITDA-Meilensteine)",
      "Retention-gebundenes Equity-Vesting",
      "Clawback-Klauseln für außergewöhnliche Ereignisse"
    ],
    "title": "Earn-out-Mechanismen"
  },
  "notes": "Hohes strategisches Interesse durch AI/Robotics-Konsolidierung; Co-Selling/Allianzen erhöhen Valuation-Optionen.",
  "options": {
    "a": {
      "points": [],
      "title": "Trade Sale (Strategic)"
    },
    "b": {
      "points": [],
      "title": "PE / Growth Buyout"
    },
    "c": {
      "points": [],
      "title": "IPO (Langfrist-Option)"
    }
  },
  "preparation": {
    "actions": [
      "Bankfähige KPIs: auditierte ARR, Churn <10%, Bruttomarge >60%",
      "Compliance-Bereitschaft: CE, AI Act, Datenschutz",
      "Datenraum: Verträge, IP, Tech-Dokumente, Security-Reports"
    ],
    "title": "Exit-Vorbereitung"
  },
  "risks": {
    "items": [
      {
        "mitigation": "Dual-Track-Prozess (IPO/Trade Sale), flexible Timing",
        "risk": "Marktfenster verschiebt sich"
      },
      {
        "mitigation": "Käuferuniversum verbreitern (strategisch/finanziell)",
        "risk": "Käuferkonzentration"
      },
      {
        "mitigation": "Frühe Zertifizierung, Legal Counsel",
        "risk": "Regulatorische Verzögerungen"
      }
    ],
    "title": "Exit-Risiken & Gegenmaßnahmen"
  },
  "roi": {
    "text": "Illustrative Szenarien zeigen attraktive Multiples unter konservativen Wachstumsannahmen.",
    "title": "ROI & Investor-Value"
  },
  "secondary": {
    "points": [
      "Teilweiser Gründerliquidität bei Series A/B",
      "Mitarbeiterliquidität über Tender Offer"
    ],
    "title": "Secondary-Optionen"
  },
  "timeline": {
    "phases": [
      {
        "activities": [
          "ARR > €10 Mio skalieren",
          "Unit Economics stabil halten"
        ],
        "period": "2026–2027"
      },
      {
        "activities": [
          "EBITDA positiv",
          "Käuferuniversum verbreitern"
        ],
        "period": "2028–2029"
      },
      {
        "activities": [
          "Exit-Fenster (IPO oder Trade Sale)"
        ],
        "period": "2030+"
      }
    ],
    "title": "Exit-Zeitplan"
  },
  "title": "Exit-Strategie",
  "valuation": {
    "methods": [
      "Umsatz-Multiples (ARR forward)",
      "Vergleichstransaktionen",
      "Discounted Cash Flow (Sensitivität)"
    ],
    "multiples": [
      "EV/ARR 8–12x",
      "EV/EBITDA 15–25x"
    ],
    "range": "€30–60 Mio (illustrativ)",
    "title": "Bewertungsansatz"
  }
} as const;

export default data;
