// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/de/gtm.ts
const data = {
  "channelMix": [
    {
      "channel": "Allianzen (OEM/Integrator)",
      "metrics": [
        "Partner‑Pipeline",
        "Co‑Seller‑Deals"
      ],
      "notes": "Hebel über bestehende Kundenbasen",
      "share": 35
    },
    {
      "channel": "Design‑Partner/Direct",
      "metrics": [
        "SQLs",
        "PoC‑Starts"
      ],
      "notes": "Schnelle Validierung, Referenzen",
      "share": 25
    },
    {
      "channel": "Developer/Marketplace",
      "metrics": [
        "SDK‑Signups",
        "Third‑party Skills"
      ],
      "notes": "Ökosystem‑Wachstum, Rev‑Share",
      "share": 15
    },
    {
      "channel": "Events & Demos",
      "metrics": [
        "Leads",
        "Demo‑Requests"
      ],
      "notes": "Live‑Erlebnis, Trust",
      "share": 10
    },
    {
      "channel": "Content/SEO/Community",
      "metrics": [
        "Visits",
        "MQL‑Rate"
      ],
      "notes": "Langfristige Demand‑Gen",
      "share": 10
    },
    {
      "channel": "Paid (Targeted ABM)",
      "metrics": [
        "CTR",
        "CPL"
      ],
      "notes": "Eng fokussiert auf ICP Accounts",
      "share": 5
    }
  ],
  "funnel": [
    {
      "metric": "Reichweite/Impressions",
      "notes": "Paid + Earned Media, Social Video Demos",
      "stage": "Awareness",
      "target": ">500k/Quartal"
    },
    {
      "metric": "Website‑Besuche / Demo‑Views",
      "notes": "SEO, Tech‑Blog, Benchmark‑Videos",
      "stage": "Interest",
      "target": ">60k/Quartal"
    },
    {
      "metric": "Qualified Leads (MQL)",
      "notes": "Lead‑Magnete, Whitepaper, Webinare",
      "stage": "Consideration",
      "target": "3.5% von Visits"
    },
    {
      "metric": "SQL/Design‑Partner",
      "notes": "Use‑Case‑Scoping, ROI‑Simulator",
      "stage": "Evaluation",
      "target": "40% der MQL"
    },
    {
      "metric": "PoC‑Start",
      "notes": "Werk‑Demos, Integrator‑Support, SLAs",
      "stage": "Pilot",
      "target": ">50% der SQL"
    },
    {
      "metric": "Multi‑Site Deployments",
      "notes": "Enablement, Training, Analytics",
      "stage": "Rollout",
      "target": ">60% der Pilots"
    },
    {
      "metric": "Net Expansion",
      "notes": "App‑Store‑Upsell, neue Skills/Use‑Cases",
      "stage": "Expansion",
      "target": ">120%"
    }
  ],
  "kpis": [
    ">99.99% Uptime (rolling 30d)",
    "<10ms Edge‑Reaktionszeit",
    ">60% Skill‑Adoption je Kunde",
    ">3 aktive Skills je Roboter nach 90 Tagen",
    "Net Expansion >120%",
    "Sales‑Cycle <90 Tage (Pilot → Rollout)",
    "PoC‑Conversion >50%"
  ],
  "phase1": [
    "Pilotprojekte mit Pflegeheimen, Hotels, Forschungsinstituten",
    "Kooperationen mit österreichischen Universitäten (TU Wien, FH Hagenberg, JKU Linz)",
    "Skalierung (Phase 2 – 2028–2029): Aufbau RaaS-Infrastruktur für B2B-Kunden, Launch Roboter-Appstore (Beta), Ziel: 20–30 Kunden in DACH-Region",
    "Expansion (Phase 3 – 2030): Eintritt in EU-Markt (Healthcare + Office), White-Label-Lösungen für internationale Partner, Appstore als Standard-Ökosystem für humanoide Roboter"
  ],
  "phases": [
    {
      "items": [
        "PoC in Logistik/Fertigung",
        "SLA/Support‑Modell definieren",
        "Partner‑Onboarding (Integratoren, OEMs)"
      ],
      "name": "Phase 1 – Piloten"
    },
    {
      "items": [
        "Developer‑SDK",
        "Third‑Party‑Skills",
        "Billing/Licensing"
      ],
      "name": "Phase 2 – App‑Store Beta"
    },
    {
      "items": [
        "Multi‑Site Deployments",
        "Analytics/KPIs",
        "Enablement & Training"
      ],
      "name": "Phase 3 – Enterprise Rollout"
    }
  ],
  "tactics": [
    "Design‑Partner‑Programm (3–5 Leitkunden)",
    "Allianzen mit Robotik‑OEMs & Integratoren",
    "Developer‑Programm für Skill‑Anbieter (Rev‑Share)",
    "Zertifizierungen/CE/AI‑Act als Marktzutrittsturbo",
    "Showcases & Demos (Messen, Labs, Video‑Katalog)",
    "Content/Demand‑Gen: Tech‑Blogs, Benchmark‑Videos, Webinar‑Series",
    "Field‑Marketing: Werks‑Demos mit OEM/Integrator vor Ort"
  ]
} as const;

export default data;
