// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/de/hero.ts
const data = {
  "subtitle": "RaaS mit Robot‑App‑Store, Policy‑Hub und <10ms Edge – sicher, auditierbar, skalierbar.",
  "title": "Humanoide Robotik als Service – App‑Store für Skills"
} as const;

export default data;
