// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/de/impact.ts
const data = {
  "description": [
    "Unsere Technologie reduziert die Implementierungskosten von Robotik-Lösungen um bis zu 70% und ermöglicht dadurch einen breiteren Zugang zu Automatisierung.",
    "Durch die Open-Source-Strategie fördern wir Innovation und Zusammenarbeit in der Robotik-Community."
  ],
  "socialImpact": [
    "Schaffung von hochqualifizierten Arbeitsplätzen im Tech-Sektor",
    "Unterstützung von Bildungseinrichtungen mit kostenlosen Lizenzen",
    "Zusammenarbeit mit gemeinnützigen Organisationen"
  ],
  "sustainabilityGoals": [
    "Reduzierung von CO2-Emissionen durch effizientere Logistik",
    "Bildungszugang durch erschwingliche Robotik-Lösungen",
    "Förderung von Inklusion durch barrierefreie Technologien"
  ],
  "title": "Wirkung & Nachhaltigkeit"
} as const;

export default data;
