// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/de/kpi.ts
const data = {
  "activeSkills": "Aktive Skills/Roboter",
  "adoption": "Skill‑Adoption",
  "latency": "Edge‑Latenz",
  "roi": "ROI",
  "throughput": "Durchsatz",
  "units": "Roboter",
  "uptime": "Uptime"
} as const;

export default data;
