// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/de/mlops.ts
const data = {
  "practices": [
    "Model‑Registry & Reproduzierbarkeit, Rollback‑Strategien",
    "A/B‑Evals, Shadow‑Mode, Datenqualitäts‑Gates",
    "Security‑Reviews & Freigabe‑Gates (Vier‑Augen‑Prinzip)"
  ],
  "stack": [
    "Policy‑Hub, Versionierung, Feature‑Flags, Canary‑Rollouts",
    "Telemetrie‑Pipelines (Logs/Traces/Metriken) & Observability",
    "CI/CD für Modelle & Skills inkl. Offline/Online‑Evals"
  ]
} as const;

export default data;
