// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/de/nav.ts
const data = {
  "brand": "SIGMACODE AI Robotics",
  "brandSubtitle": "Robotics",
  "brandTitle": "SIGMACODE AI",
  "downloadPdf": "Als PDF drucken",
  "homeAria": "{brand} – Startseite",
  "language": "Sprache",
  "mainNav": "Hauptnavigation"
} as const;

export default data;
