// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/de/pitchCover.ts
const data = {
  "open": "Pitch-Deck online öffnen",
  "subtitle": "Humanoid Robotics · App‑Store · KI‑Assistenz · Skalierbares RaaS",
  "title": "Investor Pitch"
} as const;

export default data;
