// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/de/problem.ts
const data = {
  "defaults": {
    "empty": "Keine Probleme definiert"
  },
  "overviewTitle": "Problemübersicht",
  "title": "Problem"
} as const;

export default data;
