// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/de/products.ts
const data = {
  "paragraphs": [
    "Der Roboter‑App‑Store liefert zertifizierte Skills (Greifen, Navigation, Inspektion, Handling), die ohne Produktionsstopp ausgerollt werden können.",
    "Mit dem Workflow‑Composer (Drag‑and‑Drop) entstehen End‑to‑End‑Flows, die über Flotten mit Versionierung und Monitoring ausgerollt werden.",
    "Das Developer‑SDK öffnet die Plattform für Partner: Third‑Party‑Skills mit Billing/Licensing ermöglichen Ökosystem‑Wachstum und schnelleren Value."
  ],
  "stages": [
    "Phase 1: Skill‑Basics (Greifen, Navigation, Inspektion)",
    "Phase 2: Workflow‑Composer (Drag‑and‑Drop, App‑Store‑Integration)",
    "Phase 3: Flotten‑Rollout (Policy‑Hub, Tele‑Assist, Monitoring)",
    "Phase 4: Partner‑Ökosystem (Third‑Party‑Skills, Zertifizierung)",
    "Phase 5: Enterprise‑Skalierung (SLA/Support, Multi‑Site, KPIs)"
  ]
} as const;

export default data;
