// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/de/risks.ts
const data = {
  "additional": {
    "Monitoring": "KPIs/Telemetry, A/B‑Evals, Red‑Teaming für Safety/AI",
    "ThirdParties": "Verträge/SLAs, Audit‑Trails, Pen‑Tests"
  },
  "benefits": [
    "Schnellere Zertifizierungen durch wiederverwendbare, geprüfte Module",
    "Höhere Kundentreue via messbaren ROI und planbare Rollouts",
    "Produktqualität durch Telemetrie, E2E‑Evals und Fleet‑Learning"
  ],
  "finance": {
    "cashflow": {
      "mitigation": "Hardware‑Leasing/‑Partner, gestaffelte Lieferungen, Vorauszahlungen/Deposits, striktes Working‑Capital‑Monitoring.",
      "risk": "Vorfinanzierung von Hardware/Prototypen, langer Sales‑Zyklus und Capex können Liquidität strapazieren.",
      "title": "Cashflow"
    },
    "grants": {
      "mitigation": "Hybrid‑Finanzierung (Seed + Grants), Meilenstein‑getaktete Mittelverwendung, alternative Programme (EU/Kofinanzierung).",
      "risk": "Ausbleibende oder verzögerte Förderzusagen belasten den Cash‑Runway.",
      "title": "Förderungen"
    },
    "title": "Finanzen"
  },
  "list": [
    "Technologierisiko (TRL, Sim‑zu‑Real, Safety/HRI)",
    "Go‑to‑Market (Abhängigkeit von OEM/Integratoren, Zertifizierungszyklen)",
    "Finanzierung (Hardware‑CAPEX, Skalierungskosten)",
    "Compliance (EU AI Act, CE, Cybersecurity/Privacy)",
    "Talent (DeepTech, Wettbewerb um Expert:innen)"
  ],
  "market": {
    "adoption": {
      "mitigation": "Design‑Partner‑Programm, messbare Pilot‑KPIs, Schulungen/Enablement, vorgefertigte Templates für gängige Prozesse.",
      "risk": "Enterprise‑Adoption kann sich verzögern (Change‑Management, Werkszertifizierung, interne Compliance).",
      "title": "Adoption"
    },
    "competition": {
      "mitigation": "Differenzierung über App‑Store/SDK, zertifizierte Third‑Party‑Skills, EU‑Compliance & Safety als Markttreiber, Fokus auf High‑Impact‑Workflows.",
      "risk": "Starker Wettbewerb durch OEM‑Stacks und horizontale Plattformen; Preisdruck bei Standard‑Skills.",
      "title": "Wettbewerb"
    },
    "pricing": {
      "mitigation": "Tiered + Usage‑Modell, ROI‑Simulator, Pay‑per‑Outcome‑Optionen und schlanke Einstiegspakete (PoC‑Bundles).",
      "risk": "Fehlende Zahlungsbereitschaft für bestimmte Workflows oder in frühen Phasen der Automatisierung.",
      "title": "Pricing"
    },
    "title": "Markt"
  },
  "mitigation": {
    "items": [
      "Meilensteinplan mit Evals & Risk Register (AP1–AP4)",
      "Partnerschaften (Integratoren/OEMs), Design‑Partner‑Programm",
      "Hybrid‑Finanzierung (Seed + Grants), Kostenkontrolle",
      "Provenienz/Evals, Sicherheitsprogramm, Compliance‑Dokus",
      "ESOP & Branding, Kooperationen mit Universitäten/Netzwerken"
    ],
    "title": "Gegenmaßnahmen"
  },
  "mitigationDetailed": {
    "finance": [
      "Leasing/Partnerschaften für CAPEX, Vorauszahlungen/Deposits",
      "Szenario‑Planung und Kostenkontrolle, Runway‑Alerts",
      "Mehrgleisige Förderung und Meilenstein‑Gatekeeping"
    ],
    "legal": [
      "Frühe Einbindung von Compliance/Safety‑Beauftragten",
      "Standardisierte Test‑/Abnahmeprotokolle, Audit‑Trails",
      "Vertrags‑SLAs und Haftungsregelungen mit Partnern"
    ],
    "market": [
      "Design‑Partner & Referenzen, wiederholbare Pilot‑Playbooks",
      "ROI‑Simulatoren und klare Business‑Cases pro Workflow",
      "Zertifizierungs‑Roadmaps kommunizieren (CE/AI‑Act)"
    ],
    "tech": [
      "Risk Register je Arbeitspaket (AP1–AP4) mit klaren Eigentümern",
      "Canary‑Rollouts, Feature‑Flags, schrittweise Aktivierung",
      "Evals/Red‑Teaming, formale Constraints, simulierte Edge‑Cases"
    ],
    "title": "Gegenmaßnahmen (detailliert)"
  },
  "operations": {
    "keyPeople": {
      "mitigation": "Dokumentation, Pairing/Reviews, Rotation, Notfall‑Pläne und Redundanz in kritischen Rollen.",
      "risk": "Abhängigkeit von Schlüsselpersonen erhöht Ausfall‑/Know‑how‑Risiken.",
      "title": "Key People"
    },
    "talent": {
      "mitigation": "ESOP & Employer‑Branding, Remote‑freundliche Teams, Uni‑Kooperationen, gezielte Senior‑Hires mit Multiplikator‑Effekt.",
      "risk": "Knappheit an DeepTech‑Profilen (Robotik/Controls/ML) limitiert Umsetzungstempo.",
      "title": "Talent"
    },
    "title": "Operations"
  },
  "regulatory": {
    "cert": {
      "mitigation": "Standardisierte Testpläne, Re‑Use zertifizierter Module, enge Zusammenarbeit mit Sicherheitsbeauftragten, Pilot‑Werke als Referenzen.",
      "risk": "Werksinterne Abnahmen (Safety/HRI) variieren je Standort und erfordern zusätzliche Tests.",
      "title": "Zertifizierungen"
    },
    "eu": {
      "mitigation": "Frühes Compliance‑Management, Risiko‑/Daten‑/Modell‑Governance, lückenlose Logs, Model Cards/Datasheets und CE‑Dokumentation.",
      "risk": "Fehleinstufung oder unvollständige Nachweise können Zertifizierung und Rollouts verzögern.",
      "title": "EU/AI Act"
    },
    "title": "Regulatorik"
  },
  "tech": {
    "aiSafety": {
      "mitigation": "Zonen‑/Kontaktkraft‑Guardrails, formale Constraints, Red‑Teaming & Evals, Human‑in‑the‑Loop bei riskanten Manövern, Audit‑Trail & Provenienz.",
      "risk": "Fehlverhalten lernender Policies unter Edge‑Bedingungen (Out‑of‑Distribution, Latenz, Sensorrauschen) kann Safety/HRI beeinträchtigen.",
      "title": "AI Safety"
    },
    "complexity": {
      "mitigation": "Phasenplan mit klaren Meilensteinen (AP1–AP4), frühzeitige Ende‑zu‑Ende‑Tests, Canary‑Rollouts, Tele‑Assist und robuste Observability (Tracing/Logs/Metriken).",
      "risk": "Ganzkörper‑Manipulation, Sim‑zu‑Real und Safety erhöhen die Systemkomplexität und bergen Integrations‑/Stabilitätsrisiken.",
      "title": "Komplexität"
    },
    "title": "Technologie",
    "vendors": {
      "mitigation": "Abstraktionsschicht (ROS2/Hardware‑Adapter), Multi‑Vendor‑Qualifizierung, langfristige SLAs und Second‑Source‑Strategie.",
      "risk": "Abhängigkeit von Hardware‑/Cloud‑Anbietern kann Kosten, Lieferzeiten und Roadmap beeinflussen.",
      "title": "Abhängigkeit von Anbietern"
    }
  },
  "title": "Risiken"
} as const;

export default data;
