// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/de/sections.ts
const data = {
  "appendix": "Anhang",
  "businessModel": "Geschäftsmodell",
  "capTable": "Cap Table",
  "company": "Unternehmen",
  "compliance": "Compliance",
  "costPlan": "Kostenplan",
  "cta": "Nächste Schritte",
  "dissemination": "Dissemination",
  "executive": "Zusammenfassung",
  "exit": "Exit-Strategie",
  "finance": "Finanzen",
  "gtm": "Go-to-Market",
  "impact": "Impact & Nachhaltigkeit",
  "innovation": "Innovation",
  "ipMoat": "IP & Moat",
  "market": "Markt & Wettbewerb",
  "marketCompetitive": "Wettbewerbslandschaft",
  "operations": "Operations",
  "problem": "Problem",
  "products": "Produkte",
  "responsibleAI": "Responsible AI",
  "risks": "Risiken",
  "solution": "Lösung",
  "stateOfTheArt": "Stand der Technik",
  "team": "Team",
  "teamOrg": "Team & Organisation",
  "technology": "Technologie",
  "traction": "Traction & KPIs",
  "tractionKpis": "Traction & KPIs"
} as const;

export default data;
