// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/de/teamOrg.ts
const data = {
  "founders": [
    "Ismet Mesic – CIO & CTO",
    "Medina Mesic, MSc – Co‑CEO & CMO",
    "Atifa Mesic – CFO"
  ],
  "ftePlan": [
    {
      "focus": [
        "AI/Robotik",
        "Controls",
        "Cloud"
      ],
      "roles": [
        "AI Eng",
        "Controls Eng",
        "Full‑stack",
        "PM"
      ],
      "teamSize": 6,
      "year": "Y1"
    },
    {
      "focus": [
        "Safety",
        "SDK",
        "GTM"
      ],
      "roles": [
        "Safety Eng",
        "SDK Eng",
        "Solutions",
        "Support"
      ],
      "teamSize": 10,
      "year": "Y2"
    }
  ],
  "summary": "Geschäftsführung: Medina & Atifa Mesic. Technologie & Innovation verantwortet der CIO/CTO. Marketing & Vertrieb, Finanzen & Banking sind klar zugeordnet. Fokus: sichere, auditierbare humanoide Robotik mit App‑Store‑Ökosystem.",
  "years": [
    {
      "focus": [
        "AI/Robotik",
        "Controls",
        "Cloud"
      ],
      "roles": [
        "AI Eng",
        "Controls Eng",
        "Full‑stack",
        "PM"
      ],
      "size": 6,
      "year": "Y1"
    },
    {
      "focus": [
        "Safety",
        "SDK",
        "GTM"
      ],
      "roles": [
        "Safety Eng",
        "SDK Eng",
        "Solutions"
      ],
      "size": 10,
      "year": "Y2"
    }
  ]
} as const;

export default data;
