// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/de/workPackagesDetailed.ts
const data = {
  "headersEffort": [
    "WP",
    "Rolle",
    "FTE"
  ],
  "items": [
    {
      "budget": {
        "material": 2,
        "other": 1,
        "personnel": 15,
        "subcontracting": 0
      },
      "budgetJustification": {
        "material": "Workshop-Materialien, Tools",
        "other": "Reisekosten/Kommunikation",
        "personnel": "PM/PL für Workshops und Planerstellung"
      },
      "deliverables": [
        "Anforderungsdokument",
        "Projektplan",
        "Risikoanalyse"
      ],
      "dependencies": [],
      "effort": [
        {
          "fte": 0.6,
          "role": "Projektleitung"
        },
        {
          "fte": 0.4,
          "role": "Product Manager"
        }
      ],
      "id": "WP1",
      "kpis": [
        "Scope-Abdeckung ≥ 90% (Review-Checkliste)",
        "Review-Iterationen ≤ 2 bis Freigabe"
      ],
      "milestones": [
        {
          "acceptance": "Stakeholder sign-off",
          "label": "Kickoff",
          "month": 0
        },
        {
          "acceptance": "Review abgeschlossen (alle Blocker gelöst)",
          "label": "Anforderungsdokument v1",
          "month": 1
        }
      ],
      "mitigations": [
        "Frühe Reviews",
        "Asynchrone Abstimmungen"
      ],
      "name": "Projektvorbereitung & Anforderungsanalyse",
      "objectives": [
        "Ziele und Scope abgestimmt mit Stakeholdern",
        "Risiken und Annahmen dokumentiert"
      ],
      "personMonths": [
        {
          "pm": 1.8,
          "role": "Projektleitung"
        },
        {
          "pm": 1.2,
          "role": "Product Manager"
        }
      ],
      "risks": [
        "Unklare Anforderungen",
        "Stakeholder-Verfügbarkeit"
      ],
      "scope": [
        "Workshops, Interviewleitfäden, Dokumentation",
        "Projektplan mit Meilensteinen und Abnahmen"
      ],
      "timeframe": "Monat 0–2",
      "trl": {
        "start": 2,
        "target": 3
      }
    },
    {
      "budget": {
        "material": 5,
        "other": 2,
        "personnel": 25,
        "subcontracting": 0
      },
      "budgetJustification": {
        "material": "Prototyping-Lizenzen/Tools",
        "personnel": "Architektur/Designarbeit mehrerer Senior-Rollen"
      },
      "deliverables": [
        "Technisches Konzept",
        "Systemarchitektur",
        "Schnittstellenspezifikation"
      ],
      "dependencies": [
        "WP1"
      ],
      "effort": [
        {
          "fte": 0.6,
          "role": "CIO/CTO"
        },
        {
          "fte": 0.8,
          "role": "Platform/Full‑stack"
        },
        {
          "fte": 0.6,
          "role": "Safety Engineer"
        }
      ],
      "id": "WP2",
      "kpis": [
        "Architekturentscheidungen ≤ 2 Iterationen (Entscheidungsmatrix)",
        "Schnittstellenspezifikation ≥ 90% vollständig"
      ],
      "milestones": [
        {
          "acceptance": "Entscheidungspapier freigegeben (CTO + Safety)",
          "label": "Architektur-Review",
          "month": 3
        }
      ],
      "mitigations": [
        "Spike-Prototypen",
        "Entscheidungsmatrix"
      ],
      "name": "Technische Konzeption & Architektur",
      "objectives": [
        "Zielarchitektur und Schnittstellen spezifiziert",
        "Make/Buy/Partner-Entscheidungen"
      ],
      "personMonths": [
        {
          "pm": 1.8,
          "role": "CIO/CTO"
        },
        {
          "pm": 2.4,
          "role": "Platform/Full‑stack"
        },
        {
          "pm": 1.8,
          "role": "Safety Engineer"
        }
      ],
      "risks": [
        "Technologieauswahl verzögert"
      ],
      "scope": [
        "Systemarchitektur",
        "Schnittstellen/SDK",
        "Qualitätsattribute"
      ],
      "timeframe": "Monat 3–5",
      "trl": {
        "start": 3,
        "target": 4
      }
    },
    {
      "budget": {
        "material": 10,
        "other": 5,
        "personnel": 80,
        "subcontracting": 15
      },
      "budgetJustification": {
        "material": "Compute/Cloud/Tools",
        "other": "Lizenz-/Sonstige Kosten",
        "personnel": "Hauptentwicklungsphase (AI/FS/Controls/QA)",
        "subcontracting": "Spezielle 3rd‑Party Komponenten/Integrationen"
      },
      "deliverables": [
        "Quellcode",
        "Testberichte",
        "Dokumentation"
      ],
      "dependencies": [
        "WP2"
      ],
      "effort": [
        {
          "fte": 2.5,
          "role": "AI Engineer"
        },
        {
          "fte": 2,
          "role": "Full‑stack Engineer"
        },
        {
          "fte": 1,
          "role": "Controls Engineer"
        },
        {
          "fte": 0.5,
          "role": "QA Engineer"
        }
      ],
      "id": "WP3",
      "kpis": [
        "Velocity ≥ 20 SP/Sprint (Median über 4 Sprints)",
        "Unit Coverage ≥ 60% (Core‑Module)",
        "E2E Smoke‑Suite < 10 min p95"
      ],
      "milestones": [
        {
          "acceptance": "Smoke‑Tests grün, Demo öffentlich möglich",
          "label": "MVP Feature-Set",
          "month": 8
        }
      ],
      "mitigations": [
        "Scope Cut Kriterien",
        "Integrationstest‑Stubs"
      ],
      "name": "Entwicklung & Implementierung",
      "objectives": [
        "MVP-Funktionalität geliefert",
        "CI/CD, Observability, Sicherheits-Gates aktiv"
      ],
      "personMonths": [
        {
          "pm": 20,
          "role": "AI Engineer"
        },
        {
          "pm": 16,
          "role": "Full‑stack Engineer"
        },
        {
          "pm": 8,
          "role": "Controls Engineer"
        },
        {
          "pm": 4,
          "role": "QA Engineer"
        }
      ],
      "risks": [
        "Feature-Creep",
        "Integration Drittsysteme"
      ],
      "scope": [
        "Kernfeatures",
        "Tests",
        "Dokumentation"
      ],
      "timeframe": "Monat 6–13",
      "trl": {
        "start": 4,
        "target": 6
      }
    },
    {
      "budget": {
        "material": 5,
        "other": 2,
        "personnel": 30,
        "subcontracting": 5
      },
      "budgetJustification": {
        "material": "Testumgebung/Tools",
        "personnel": "Test-/SRE‑Aufwände für Qualität & Stabilität",
        "subcontracting": "Externe Audits/Tests (falls erforderlich)"
      },
      "deliverables": [
        "Testberichte",
        "Bug‑Reports",
        "Freigabedokumentation"
      ],
      "dependencies": [
        "WP3"
      ],
      "effort": [
        {
          "fte": 1.5,
          "role": "QA Engineer"
        },
        {
          "fte": 0.5,
          "role": "SRE/MLOps"
        }
      ],
      "id": "WP4",
      "kpis": [
        "Defect Leakage < 3% (Staging→Prod)",
        "MTTR < 1 Tag (p95)",
        "Reliability Score ≥ 0.98"
      ],
      "milestones": [
        {
          "acceptance": "CI Coverage ≥ 70% (Core‑Flows)",
          "label": "Coverage 70%",
          "month": 12
        }
      ],
      "mitigations": [
        "Canary/Chaos‑Tests",
        "Isolierte Pipelines"
      ],
      "name": "Testing & Qualitätssicherung",
      "objectives": [
        "Qualität belegt",
        "Freigabekriterien erfüllt"
      ],
      "personMonths": [
        {
          "pm": 6,
          "role": "QA Engineer"
        },
        {
          "pm": 2,
          "role": "SRE/MLOps"
        }
      ],
      "risks": [
        "Instabile Testumgebung"
      ],
      "scope": [
        "Systemtests",
        "Sicherheitsprüfungen",
        "Freigabedoku"
      ],
      "timeframe": "Monat 11–14",
      "trl": {
        "start": 6,
        "target": 7
      }
    },
    {
      "budget": {
        "material": 3,
        "other": 2,
        "personnel": 15,
        "subcontracting": 0
      },
      "budgetJustification": {
        "material": "Enablement‑Materialien",
        "other": "Reise/Support",
        "personnel": "Training/Rollout"
      },
      "deliverables": [
        "Schulungsunterlagen",
        "Benutzerhandbuch",
        "Abschlussbericht"
      ],
      "dependencies": [
        "WP4"
      ],
      "effort": [
        {
          "fte": 0.5,
          "role": "Projektleitung"
        },
        {
          "fte": 1,
          "role": "Solutions Engineer"
        }
      ],
      "id": "WP5",
      "kpis": [
        "NPS ≥ 30",
        ">= 2 Referenzkunden mit schriftlichem Statement",
        "Onboarding‑Zeit ≤ 1 Tag/Kunde"
      ],
      "milestones": [
        {
          "acceptance": "Abnahme durch Stakeholder (SLA vereinbart)",
          "label": "Go‑Live",
          "month": 15
        }
      ],
      "mitigations": [
        "Enablement‑Plan",
        "Support‑SLAs"
      ],
      "name": "Einführung & Schulung",
      "objectives": [
        "Go‑Live",
        "User Adoption/Training"
      ],
      "personMonths": [
        {
          "pm": 1,
          "role": "Projektleitung"
        },
        {
          "pm": 2,
          "role": "Solutions Engineer"
        }
      ],
      "risks": [
        "Geringe Adoption"
      ],
      "scope": [
        "Schulung",
        "Benutzerhandbuch",
        "Abschlussbericht"
      ],
      "timeframe": "Monat 15–16",
      "trl": {
        "start": 7,
        "target": 8
      }
    }
  ],
  "note": "Struktur: Ziele/Scope, Deliverables, Aufwand (FTE), Abhängigkeiten, Risiken, KPIs, Milestones, Budget",
  "title": "Arbeitspakete – Detailliert"
} as const;

export default data;
