// Auto-generated by sort-i18n-ts.js
// File: src/i18n/locales/de/workPackages.ts
const data = {
  "headers": [
    "WP",
    "Bezeichnung",
    "Zeitplan",
    "Deliverables",
    "Budget (k€)"
  ],
  "rows": [
    {
      "budget": 18,
      "deliverables": [
        "Anforderungsdokument",
        "Projektplan",
        "Risikoanalyse"
      ],
      "id": "WP1",
      "name": "Projektvorbereitung & Anforderungsanalyse",
      "timeline": "M0–M2"
    },
    {
      "budget": 32,
      "deliverables": [
        "Technisches Konzept",
        "Systemarchitektur",
        "Schnittstellen"
      ],
      "id": "WP2",
      "name": "Technische Konzeption & Architektur",
      "timeline": "M3–M5"
    },
    {
      "budget": 110,
      "deliverables": [
        "Kernfeatures",
        "Tests",
        "Dokumentation"
      ],
      "id": "WP3",
      "name": "Entwicklung & Implementierung",
      "timeline": "M6–M13"
    },
    {
      "budget": 42,
      "deliverables": [
        "Testberichte",
        "Bug-Reports",
        "Freigabe"
      ],
      "id": "WP4",
      "name": "Testing & Qualitätssicherung",
      "timeline": "M11–M14"
    },
    {
      "budget": 20,
      "deliverables": [
        "Schulungen",
        "Handbuch",
        "Abschlussbericht"
      ],
      "id": "WP5",
      "name": "Einführung & Schulung",
      "timeline": "M15–M16"
    }
  ],
  "title": "Arbeitspakete & Budget (indicative)"
} as const;

export default data;
