name: i18n Validation

on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["main", "master"]

jobs:
  i18n-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Enable Corepack (pnpm)
        run: corepack enable

      - name: Activate pnpm version
        run: corepack prepare pnpm@9.12.3 --activate

      - name: Verify pnpm
        run: pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run i18n schema validation
        run: pnpm run i18n:schema

      - name: Run i18n keys validation
        run: pnpm run i18n:check
