name: Vercel Deploy

on:
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    name: Build and Deploy to Vercel
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fail fast if Vercel secrets are missing
        run: |
          set -euo pipefail
          missing=0
          for v in VERCEL_TOKEN VERCEL_PROJECT_ID VERCEL_ORG_ID; do
            if [ -z "${!v:-}" ]; then
              echo "::error::Missing required secret: $v"
              missing=1
            fi
          done
          if [ "$missing" -ne 0 ]; then
            echo "One or more Vercel secrets are missing. Add them under Settings → Secrets and variables → Actions."
            exit 1
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack (pnpm)
        run: corepack enable

      - name: Activate pnpm version
        run: corepack prepare pnpm@9.12.3 --activate

      - name: Verify pnpm
        run: pnpm -v

      - name: Verify Vercel CLI auth
        run: npx vercel --version

      - name: Link project (no prompt)
        run: |
          npx vercel link --yes \
            --cwd=. \
            --project=$VERCEL_PROJECT_ID \
            --scope=$VERCEL_ORG_ID \
            --token=$VERCEL_TOKEN

      - name: Pull Vercel Environment Information
        run: |
          npx vercel pull --yes \
            --environment=production \
            --cwd=. \
            --project=$VERCEL_PROJECT_ID \
            --scope=$VERCEL_ORG_ID \
            --token=$VERCEL_TOKEN

      - name: Install dependencies
        working-directory: .
        run: pnpm install --frozen-lockfile

      - name: Build
        working-directory: .
        run: pnpm build

      - name: Deploy to Vercel (prebuilt)
        run: |
          npx vercel deploy --prebuilt \
            --prod \
            --cwd=. \
            --project=$VERCEL_PROJECT_ID \
            --scope=$VERCEL_ORG_ID \
            --token=$VERCEL_TOKEN

